// generated by @readrun/widgets — edit .readrun/widgets/bayes-coin.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/bayes-coin.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// src/figura/math/gamma.ts
var LG_G = 7;
var LG_C = [
  0.9999999999998099,
  676.5203681218851,
  -1259.1392167224028,
  771.3234287776531,
  -176.6150291621406,
  12.507343278686905,
  -0.13857109526572012,
  9984369578019572e-21,
  15056327351493116e-23
];
function logGamma(x) {
  if (x < 0.5) {
    return Math.log(Math.PI / Math.sin(Math.PI * x)) - logGamma(1 - x);
  }
  x -= 1;
  let a = LG_C[0];
  const t = x + LG_G + 0.5;
  for (let i = 1; i < 9; i++) a += LG_C[i] / (x + i);
  return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a);
}
function logBeta(a, b) {
  return logGamma(a) + logGamma(b) - logGamma(a + b);
}
function betaPdf(x, a, b) {
  if (x <= 0 || x >= 1) return 0;
  return Math.exp((a - 1) * Math.log(x) + (b - 1) * Math.log(1 - x) - logBeta(a, b));
}

// readrun-docs/.readrun/widgets/bayes-coin.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
function BayesCoin() {
  const W = 580;
  const H = 320;
  const [trueP, setTrueP] = (0, import_react4.useState)(0.65);
  const [priorA, setPriorA] = (0, import_react4.useState)(2);
  const [priorB, setPriorB] = (0, import_react4.useState)(2);
  const [obs, setObs] = (0, import_react4.useState)({ heads: 0, tails: 0 });
  function flip(n) {
    let h = 0;
    for (let i = 0; i < n; i++) if (Math.random() < trueP) h++;
    setObs((o) => ({ heads: o.heads + h, tails: o.tails + (n - h) }));
  }
  const a = priorA + obs.heads;
  const b = priorB + obs.tails;
  const N = 200;
  const xs = Array.from({ length: N }, (_, i) => i / (N - 1));
  const ys = xs.map((x) => betaPdf(x, a, b));
  const priorYs = xs.map((x) => betaPdf(x, priorA, priorB));
  const yMax = Math.max(...ys, ...priorYs) * 1.08;
  const toX = (x) => x * W;
  const toY = (y) => H - y / yMax * H * 0.9 - 12;
  const path = (vs) => xs.map((x, i) => `${toX(x)},${toY(vs[i])}`).join(" ");
  const mean = a / (a + b);
  const variance = a * b / ((a + b) * (a + b) * (a + b + 1));
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Bayesian Coin",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "flips", value: obs.heads + obs.tails }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u03BC", value: mean.toFixed(3), color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u03C3", value: Math.sqrt(variance).toFixed(3), color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Each flip updates a Beta posterior. Watch the curve concentrate around the true bias as evidence accumulates. The prior (dotted) reflects what you believed before any data." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H - 12, x2: W, y2: H - 12, stroke: "var(--viz-axis)", strokeWidth: "1" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "line",
              {
                x1: toX(trueP),
                y1: 0,
                x2: toX(trueP),
                y2: H - 12,
                stroke: "var(--viz-positive)",
                strokeWidth: "1.5",
                strokeDasharray: "6 4"
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("text", { x: toX(trueP) + 4, y: 14, fontSize: "11", fill: "var(--viz-positive)", children: [
              "true p = ",
              trueP.toFixed(2)
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("polyline", { points: path(priorYs), fill: "none", stroke: "var(--viz-trace-2)", strokeWidth: "1.5", strokeDasharray: "4 4", opacity: "0.7" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("polyline", { points: path(ys), fill: "none", stroke: "var(--viz-trace)", strokeWidth: "2.6" })
          ] }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 240, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "True Bias" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "true p", min: 0.05, max: 0.95, step: 0.01, value: trueP, onChange: setTrueP }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 12 }, children: "Prior Beta(\u03B1, \u03B2)" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B1 prior", min: 0.5, max: 10, step: 0.1, value: priorA, onChange: setPriorA }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B2 prior", min: 0.5, max: 10, step: 0.1, value: priorB, onChange: setPriorB }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 12 }, children: "Observations" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 8, marginBottom: 6, fontSize: 11, color: "var(--text-muted)" }, children: [
              "heads: ",
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { style: { color: "var(--viz-positive)" }, children: obs.heads }),
              "tails: ",
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { style: { color: "var(--viz-negative)" }, children: obs.tails })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap" }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => flip(1), children: "Flip \xD71" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => flip(10), children: "\xD710" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => flip(100), children: "\xD7100" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setObs({ heads: 0, tails: 0 }), children: "Reset" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Beta(1,1) is the uninformative prior (flat). Stronger priors (e.g. \u03B1=\u03B2=10) take more evidence to overcome. The posterior mean = (\u03B1 + h) / (\u03B1 + \u03B2 + h + t)."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<BayesCoin />);
