// generated by @readrun/widgets — edit .readrun/widgets/cellular-automaton.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/cellular-automaton.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/cellular-automaton.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
function elementaryRule(rule, l, c, r) {
  const idx = l << 2 | c << 1 | r;
  return rule >> idx & 1;
}
function lifeStep(grid, w, h) {
  const next = new Uint8Array(grid.length);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      let n = 0;
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          if (!dx && !dy) continue;
          const nx = (x + dx + w) % w;
          const ny = (y + dy + h) % h;
          n += grid[ny * w + nx];
        }
      }
      const cur = grid[y * w + x];
      next[y * w + x] = cur && (n === 2 || n === 3) || !cur && n === 3 ? 1 : 0;
    }
  }
  return next;
}
function CellularAutomaton() {
  const W = 600;
  const H = 320;
  const [mode, setMode] = (0, import_react4.useState)("1d");
  const [rule, setRule] = (0, import_react4.useState)(110);
  const cells1d = 120;
  const rows = 60;
  const grid1d = (0, import_react4.useMemo)(() => {
    const out = new Uint8Array(cells1d * rows);
    out[Math.floor(cells1d / 2)] = 1;
    for (let r = 1; r < rows; r++) {
      for (let c = 0; c < cells1d; c++) {
        const l = out[(r - 1) * cells1d + (c - 1 + cells1d) % cells1d];
        const m = out[(r - 1) * cells1d + c];
        const right = out[(r - 1) * cells1d + (c + 1) % cells1d];
        out[r * cells1d + c] = elementaryRule(rule, l, m, right);
      }
    }
    return out;
  }, [rule]);
  const lifeW = 60;
  const lifeH = 32;
  const [life, setLife] = (0, import_react4.useState)(() => randomLife(lifeW, lifeH));
  const [running, setRunning] = (0, import_react4.useState)(false);
  const [gen, setGen] = (0, import_react4.useState)(0);
  (0, import_react4.useEffect)(() => {
    if (mode !== "life" || !running) return;
    const id = window.setInterval(() => {
      setLife((g) => lifeStep(g, lifeW, lifeH));
      setGen((g) => g + 1);
    }, 120);
    return () => window.clearInterval(id);
  }, [mode, running]);
  function randomLife(w, h) {
    const out = new Uint8Array(w * h);
    for (let i = 0; i < out.length; i++) out[i] = Math.random() < 0.32 ? 1 : 0;
    return out;
  }
  function clearLife() {
    setLife(new Uint8Array(lifeW * lifeH));
    setGen(0);
  }
  function step() {
    setLife((g) => lifeStep(g, lifeW, lifeH));
    setGen((g) => g + 1);
  }
  const cw = W / cells1d;
  const ch = H / rows;
  const lcw = W / lifeW;
  const lch = H / lifeH;
  function lifeClick(e) {
    const rect = e.currentTarget.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (W / rect.width);
    const sy = (e.clientY - rect.top) * (H / rect.height);
    const c = Math.floor(sx / lcw);
    const r = Math.floor(sy / lch);
    const ng = new Uint8Array(life);
    ng[r * lifeW + c] = ng[r * lifeW + c] ? 0 : 1;
    setLife(ng);
  }
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Cellular Automaton",
      meta: mode === "1d" ? /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "rule", value: rule, color: "var(--viz-trace)" }) : /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "gen", value: gen, color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "alive", value: Array.from(life).reduce((a, b) => a + b, 0) })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Tiny rules, complex behaviour. Elementary CAs (Wolfram numbering) operate on a 1D row; Conway's Life on a 2D grid. Toggle modes; in Life mode, click cells to seed." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
          Tabs,
          {
            value: mode,
            onChange: (id) => setMode(id),
            items: [
              { id: "1d", label: "1D Elementary" },
              { id: "life", label: "Game of Life" }
            ]
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%", cursor: mode === "life" ? "pointer" : "default" }, onClick: mode === "life" ? lifeClick : void 0, children: mode === "1d" ? Array.from({ length: rows }).map(
            (_, r) => Array.from({ length: cells1d }).map(
              (_2, c) => grid1d[r * cells1d + c] ? /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("rect", { x: c * cw, y: r * ch, width: cw + 0.5, height: ch + 0.5, fill: "var(--viz-trace)" }, `${r}-${c}`) : null
            )
          ) : Array.from({ length: lifeH }).map(
            (_, r) => Array.from({ length: lifeW }).map(
              (_2, c) => life[r * lifeW + c] ? /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("rect", { x: c * lcw, y: r * lch, width: lcw - 0.5, height: lch - 0.5, fill: "var(--viz-positive)" }, `${r}-${c}`) : /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("rect", { x: c * lcw, y: r * lch, width: lcw - 0.5, height: lch - 0.5, fill: "transparent", stroke: "var(--border)", strokeWidth: "0.3" }, `${r}-${c}`)
            )
          ) }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Panel, { minWidth: 220, children: mode === "1d" ? /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Rule (0\u2013255)" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "rule", min: 0, max: 255, step: 1, value: rule, onChange: setRule, format: (v) => `${v}` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 8 }, children: [30, 90, 110, 150, 184].map((r) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setRule(r), children: r }, r)) }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Rule 30 is chaotic (used in some PRNGs). Rule 90 produces a Sierpinski triangle. Rule 110 is Turing-complete. Rule 184 models simple traffic flow."
            ] })
          ] }) : /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Life" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 4 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setRunning((r) => !r), children: running ? "Pause" : "Play" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: step, children: "Step" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => {
                setLife(randomLife(lifeW, lifeH));
                setGen(0);
              }, children: "Random" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: clearLife, children: "Clear" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Click cells to draw. The four rules: live with 2-3 neighbours survives; dead with exactly 3 neighbours becomes alive; everything else dies or stays dead. Simple rules \u2192 gliders, oscillators, methuselahs."
            ] })
          ] }) })
        ] })
      ]
    }
  );
}
render(<CellularAutomaton />);
