// generated by @readrun/widgets — edit .readrun/widgets/dijkstra-pathfinder.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key2 of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key2) && key2 !== except)
        __defProp(to, key2, { get: () => from[key2], enumerable: !(desc = __getOwnPropDesc(from, key2)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/dijkstra-pathfinder.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function LegendDot({ color, label }) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-legend-dot" }, /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-dot", style: { background: color } }), label);
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/dijkstra-pathfinder.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var COLS = 36;
var ROWS = 22;
function key(r, c) {
  return r * COLS + c;
}
function neighbours(r, c) {
  const out = [];
  if (r > 0) out.push([r - 1, c]);
  if (r < ROWS - 1) out.push([r + 1, c]);
  if (c > 0) out.push([r, c - 1]);
  if (c < COLS - 1) out.push([r, c + 1]);
  return out;
}
function search(walls, start, goal, algo) {
  const visited = /* @__PURE__ */ new Set();
  const cameFrom = /* @__PURE__ */ new Map();
  const cost = /* @__PURE__ */ new Map();
  const queue = [];
  cost.set(key(start[0], start[1]), 0);
  queue.push({ k: key(start[0], start[1]), r: start[0], c: start[1], pri: 0 });
  while (queue.length) {
    queue.sort((a, b) => a.pri - b.pri);
    const cur = queue.shift();
    if (visited.has(cur.k)) continue;
    visited.add(cur.k);
    if (cur.r === goal[0] && cur.c === goal[1]) break;
    for (const [nr, nc] of neighbours(cur.r, cur.c)) {
      const nk = key(nr, nc);
      if (walls.has(nk) || visited.has(nk)) continue;
      const newCost = (cost.get(cur.k) || 0) + 1;
      if (!cost.has(nk) || newCost < cost.get(nk)) {
        cost.set(nk, newCost);
        cameFrom.set(nk, cur.k);
        let pri = newCost;
        if (algo === "bfs") pri = newCost;
        if (algo === "dijkstra") pri = newCost;
        if (algo === "astar") pri = newCost + Math.abs(nr - goal[0]) + Math.abs(nc - goal[1]);
        queue.push({ k: nk, r: nr, c: nc, pri });
      }
    }
  }
  const path = [];
  const goalK = key(goal[0], goal[1]);
  if (visited.has(goalK)) {
    let k = goalK;
    while (k !== void 0) {
      path.push(k);
      k = cameFrom.get(k);
    }
    path.reverse();
  }
  return { visited, path };
}
function DijkstraPathfinder() {
  const W = 540;
  const H = 340;
  const cellW = W / COLS;
  const cellH = H / ROWS;
  const [walls, setWalls] = (0, import_react4.useState)(() => /* @__PURE__ */ new Set());
  const [start, setStart] = (0, import_react4.useState)([10, 4]);
  const [goal, setGoal] = (0, import_react4.useState)([10, 30]);
  const [algo, setAlgo] = (0, import_react4.useState)("astar");
  const dragRef = (0, import_react4.useRef)({ mode: "wall", on: false });
  const result = (0, import_react4.useMemo)(() => search(walls, start, goal, algo), [walls, start, goal, algo]);
  function pos(e, svg) {
    const rect = svg.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (W / rect.width);
    const sy = (e.clientY - rect.top) * (H / rect.height);
    return [Math.floor(sy / cellH), Math.floor(sx / cellW)];
  }
  function down(e) {
    const [r, c] = pos(e, e.currentTarget);
    const k = key(r, c);
    if (r === start[0] && c === start[1]) {
      dragRef.current = { mode: "start", on: true };
      return;
    }
    if (r === goal[0] && c === goal[1]) {
      dragRef.current = { mode: "goal", on: true };
      return;
    }
    if (walls.has(k)) {
      dragRef.current = { mode: "erase", on: true };
      const ns = new Set(walls);
      ns.delete(k);
      setWalls(ns);
    } else {
      dragRef.current = { mode: "wall", on: true };
      const ns = new Set(walls);
      ns.add(k);
      setWalls(ns);
    }
  }
  function move(e) {
    if (!dragRef.current.on) return;
    const [r, c] = pos(e, e.currentTarget);
    const k = key(r, c);
    if (dragRef.current.mode === "start") setStart([r, c]);
    else if (dragRef.current.mode === "goal") setGoal([r, c]);
    else if (dragRef.current.mode === "wall") {
      if (!walls.has(k) && !(r === start[0] && c === start[1]) && !(r === goal[0] && c === goal[1])) {
        const ns = new Set(walls);
        ns.add(k);
        setWalls(ns);
      }
    } else if (dragRef.current.mode === "erase") {
      if (walls.has(k)) {
        const ns = new Set(walls);
        ns.delete(k);
        setWalls(ns);
      }
    }
  }
  function up() {
    dragRef.current.on = false;
  }
  function clearWalls() {
    setWalls(/* @__PURE__ */ new Set());
  }
  function maze() {
    const ns = /* @__PURE__ */ new Set();
    for (let r = 0; r < ROWS; r++) {
      for (let c = 0; c < COLS; c++) {
        if (Math.random() < 0.3 && !(r === start[0] && c === start[1]) && !(r === goal[0] && c === goal[1])) {
          ns.add(key(r, c));
        }
      }
    }
    setWalls(ns);
  }
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Pathfinder",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "visited", value: result.visited.size, color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "path", value: result.path.length, color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Click and drag to draw walls. Drag the green start or red goal to move them. Switch the search algorithm \u2014 BFS is uninformed, Dijkstra accounts for cost, A* uses a Manhattan heuristic." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
          Tabs,
          {
            value: algo,
            onChange: (id) => setAlgo(id),
            items: [
              { id: "bfs", label: "BFS" },
              { id: "dijkstra", label: "Dijkstra" },
              { id: "astar", label: "A*" }
            ]
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "svg",
            {
              viewBox: `0 0 ${W} ${H}`,
              width: W,
              height: H,
              style: { display: "block", maxWidth: "100%", touchAction: "none", cursor: "crosshair" },
              onPointerDown: down,
              onPointerMove: move,
              onPointerUp: up,
              onPointerLeave: up,
              children: Array.from({ length: ROWS }).map(
                (_, r) => Array.from({ length: COLS }).map((_2, c) => {
                  const k = key(r, c);
                  let fill = "var(--bg)";
                  if (walls.has(k)) fill = "var(--text)";
                  else if (result.path.includes(k)) fill = "var(--viz-warn)";
                  else if (result.visited.has(k)) fill = "var(--viz-trace)";
                  if (r === start[0] && c === start[1]) fill = "var(--viz-positive)";
                  if (r === goal[0] && c === goal[1]) fill = "var(--viz-negative)";
                  const opacity = result.visited.has(k) && !result.path.includes(k) && !walls.has(k) ? 0.32 : 1;
                  return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                    "rect",
                    {
                      x: c * cellW,
                      y: r * cellH,
                      width: cellW - 0.5,
                      height: cellH - 0.5,
                      fill,
                      fillOpacity: opacity,
                      stroke: "var(--border)",
                      strokeWidth: "0.5"
                    },
                    k
                  );
                })
              )
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Actions" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap" }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: clearWalls, children: "Clear walls" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: maze, children: "Random maze" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 16 }, children: "Legend" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-positive)", label: "start" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-negative)", label: "goal" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--text)", label: "wall" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-trace)", label: "explored" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-warn)", label: "final path" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " BFS expands in a uniform circle (no edge weights). Dijkstra does the same on an unweighted grid. A* targets the goal \u2014 explored area shrinks dramatically because the heuristic prunes obviously-bad branches."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<DijkstraPathfinder />);
