// generated by @readrun/widgets — edit .readrun/widgets/distribution-explorer.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/distribution-explorer.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}
function ToggleRow({
  checked,
  onChange,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement(
    "label",
    {
      style: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 11,
        color: "var(--text-muted)",
        cursor: "pointer"
      }
    },
    /* @__PURE__ */ import_react3.default.createElement("input", { type: "checkbox", checked, onChange: (e) => onChange(e.target.checked) }),
    children
  );
}

// src/figura/math/gamma.ts
var LG_G = 7;
var LG_C = [
  0.9999999999998099,
  676.5203681218851,
  -1259.1392167224028,
  771.3234287776531,
  -176.6150291621406,
  12.507343278686905,
  -0.13857109526572012,
  9984369578019572e-21,
  15056327351493116e-23
];
function logGamma(x) {
  if (x < 0.5) {
    return Math.log(Math.PI / Math.sin(Math.PI * x)) - logGamma(1 - x);
  }
  x -= 1;
  let a = LG_C[0];
  const t = x + LG_G + 0.5;
  for (let i = 1; i < 9; i++) a += LG_C[i] / (x + i);
  return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a);
}
function logBeta(a, b) {
  return logGamma(a) + logGamma(b) - logGamma(a + b);
}
function betaPdf(x, a, b) {
  if (x <= 0 || x >= 1) return 0;
  return Math.exp((a - 1) * Math.log(x) + (b - 1) * Math.log(1 - x) - logBeta(a, b));
}
function gammaPdf(x, k, theta) {
  if (x <= 0) return 0;
  return Math.exp((k - 1) * Math.log(x) - x / theta - logGamma(k) - k * Math.log(theta));
}
function normalPdf(x, mu, sigma) {
  const z = (x - mu) / sigma;
  return Math.exp(-0.5 * z * z) / (sigma * Math.sqrt(2 * Math.PI));
}
function exponentialPdf(x, lambda) {
  if (x < 0) return 0;
  return lambda * Math.exp(-lambda * x);
}

// src/figura/math/random.ts
function boxMuller(rng = Math.random) {
  let u = 0;
  let v = 0;
  while (u === 0) u = rng();
  while (v === 0) v = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}
function sampleNormal(mu = 0, sigma = 1, rng = Math.random) {
  return mu + sigma * boxMuller(rng);
}
function sampleGamma(k, theta = 1, rng = Math.random) {
  if (k < 1) {
    return sampleGamma(k + 1, theta, rng) * Math.pow(rng(), 1 / k);
  }
  const d = k - 1 / 3;
  const c = 1 / Math.sqrt(9 * d);
  while (true) {
    let x;
    let v;
    do {
      x = boxMuller(rng);
      v = 1 + c * x;
    } while (v <= 0);
    v = v * v * v;
    const u = rng();
    if (u < 1 - 0.0331 * x * x * x * x) return d * v * theta;
    if (Math.log(u) < 0.5 * x * x + d * (1 - v + Math.log(v))) return d * v * theta;
  }
}
function sampleBeta(a, b, rng = Math.random) {
  const x = sampleGamma(a, 1, rng);
  const y = sampleGamma(b, 1, rng);
  return x / (x + y);
}
function sampleExponential(lambda, rng = Math.random) {
  return -Math.log(1 - rng()) / lambda;
}

// readrun-docs/.readrun/widgets/distribution-explorer.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var DISTS = [
  { id: "normal", label: "Normal" },
  { id: "beta", label: "Beta" },
  { id: "gamma", label: "Gamma" },
  { id: "exponential", label: "Exponential" }
];
var DEFAULTS = {
  mu: 0,
  sigma: 1,
  alpha: 2,
  beta: 5,
  k: 2,
  theta: 1.5,
  lambda: 1
};
function DistributionExplorer() {
  const W = 620;
  const H = 320;
  const [dist, setDist] = (0, import_react4.useState)("normal");
  const [s, setS] = (0, import_react4.useState)(DEFAULTS);
  const [view, setView] = (0, import_react4.useState)("pdf");
  const [logY, setLogY] = (0, import_react4.useState)(false);
  const [a, setA] = (0, import_react4.useState)(-0.5);
  const [b, setB] = (0, import_react4.useState)(0.5);
  const [hist, setHist] = (0, import_react4.useState)([]);
  const svgRef = (0, import_react4.useRef)(null);
  const range = (0, import_react4.useMemo)(() => {
    if (dist === "normal") return [s.mu - 4 * s.sigma, s.mu + 4 * s.sigma];
    if (dist === "beta") return [0, 1];
    if (dist === "gamma") return [0, Math.max(8, s.k * s.theta * 4)];
    return [0, Math.max(6, 6 / s.lambda)];
  }, [dist, s]);
  const pdfFn = (x) => {
    if (dist === "normal") return normalPdf(x, s.mu, s.sigma);
    if (dist === "beta") return betaPdf(x, s.alpha, s.beta);
    if (dist === "gamma") return gammaPdf(x, s.k, s.theta);
    return exponentialPdf(x, s.lambda);
  };
  const samples = (0, import_react4.useMemo)(() => {
    const out = [];
    for (let i = 0; i < 600; i++) {
      if (dist === "normal") out.push(sampleNormal(s.mu, s.sigma));
      else if (dist === "beta") out.push(sampleBeta(s.alpha, s.beta));
      else if (dist === "gamma") out.push(sampleGamma(s.k, s.theta));
      else out.push(sampleExponential(s.lambda));
    }
    return out;
  }, [dist, s, hist]);
  const N = 220;
  const pts = (0, import_react4.useMemo)(() => {
    const ys = new Array(N);
    let yMax = 0;
    let cum = 0;
    const step = (range[1] - range[0]) / N;
    for (let i = 0; i < N; i++) {
      const x = range[0] + i * step;
      ys[i] = pdfFn(x);
      if (ys[i] > yMax) yMax = ys[i];
    }
    if (view === "cdf") {
      let acc = 0;
      const total = ys.reduce((a2, b2) => a2 + b2, 0) * step;
      for (let i = 0; i < N; i++) {
        acc += ys[i] * step;
        ys[i] = acc / total;
      }
      yMax = 1;
    }
    return { ys, yMax: yMax * 1.08, step };
  }, [pdfFn, range, view]);
  const toX = (x) => (x - range[0]) / (range[1] - range[0]) * W;
  const toY = (y) => {
    if (logY && view === "pdf") {
      const ly = Math.log10(y + 1e-6);
      const lyMax = Math.log10(pts.yMax + 1e-6);
      const lyMin = -3;
      return H - (ly - lyMin) / (lyMax - lyMin) * H * 0.92 - 8;
    }
    return H - y / pts.yMax * H * 0.92 - 8;
  };
  const polyPts = [];
  for (let i = 0; i < N; i++) {
    const x = range[0] + i * pts.step;
    polyPts.push(`${toX(x)},${toY(pts.ys[i])}`);
  }
  const shadeArea = (() => {
    if (view !== "pdf") return null;
    const aIdx = Math.max(0, Math.min(N - 1, Math.round((a - range[0]) / (range[1] - range[0]) * N)));
    const bIdx = Math.max(0, Math.min(N - 1, Math.round((b - range[0]) / (range[1] - range[0]) * N)));
    const lo = Math.min(aIdx, bIdx);
    const hi = Math.max(aIdx, bIdx);
    let prob = 0;
    const segs = [];
    segs.push(`${toX(range[0] + lo * pts.step)},${H - 8}`);
    for (let i = lo; i <= hi; i++) {
      const x = range[0] + i * pts.step;
      segs.push(`${toX(x)},${toY(pts.ys[i])}`);
      prob += pts.ys[i] * pts.step;
    }
    segs.push(`${toX(range[0] + hi * pts.step)},${H - 8}`);
    return { polygon: segs.join(" "), prob };
  })();
  const bins = 26;
  const histCounts = new Array(bins).fill(0);
  const sMin = range[0];
  const sMax = range[1];
  const bw = (sMax - sMin) / bins;
  for (const v of samples) {
    if (v < sMin || v > sMax) continue;
    const i = Math.min(bins - 1, Math.floor((v - sMin) / bw));
    histCounts[i]++;
  }
  const histMaxNorm = Math.max(...histCounts) || 1;
  function setParam(k, v) {
    setS((p) => ({ ...p, [k]: v }));
  }
  const onSvgPointerDown = (e) => {
    if (!svgRef.current || view !== "pdf") return;
    const rect = svgRef.current.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (W / rect.width);
    const wx = range[0] + sx / W * (range[1] - range[0]);
    const dA = Math.abs(wx - a);
    const dB = Math.abs(wx - b);
    const which = dA < dB ? "a" : "b";
    const move = (ev) => {
      const sx2 = (ev.clientX - rect.left) * (W / rect.width);
      const wx2 = range[0] + sx2 / W * (range[1] - range[0]);
      if (which === "a") setA(wx2);
      else setB(wx2);
    };
    const up = () => {
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
    };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Distribution Explorer",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "dist", value: dist, color: "var(--viz-trace)" }),
        shadeArea && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "P(a<X<b)", value: shadeArea.prob.toFixed(3), color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Pick a distribution. Drag the cursors on the curve to compute P(a<X<b). Resample to refresh the histogram. Switch to CDF for a cumulative view." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Tabs, { value: dist, onChange: (id) => setDist(id), items: DISTS }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
            "svg",
            {
              ref: svgRef,
              viewBox: `0 0 ${W} ${H}`,
              width: W,
              height: H,
              style: { display: "block", touchAction: "none", maxWidth: "100%" },
              onPointerDown: onSvgPointerDown,
              children: [
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("g", { children: histCounts.map((c, i) => {
                  const x = toX(sMin + i * bw);
                  const w = W / bins - 2;
                  const h = c / histMaxNorm * H * 0.55;
                  return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                    "rect",
                    {
                      x: x + 1,
                      y: H - 8 - h,
                      width: w,
                      height: h,
                      fill: "var(--viz-trace-2)",
                      fillOpacity: "0.3"
                    },
                    i
                  );
                }) }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H - 8, x2: W, y2: H - 8, stroke: "var(--viz-axis)", strokeWidth: "1" }),
                shadeArea && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("polygon", { points: shadeArea.polygon, fill: "var(--viz-warn)", fillOpacity: "0.28" }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("polyline", { points: polyPts.join(" "), fill: "none", stroke: "var(--viz-trace)", strokeWidth: "2.4" }),
                view === "pdf" && /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: toX(a), y1: 0, x2: toX(a), y2: H - 8, stroke: "var(--viz-warn)", strokeWidth: "1.5", strokeDasharray: "3 3" }),
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: toX(b), y1: 0, x2: toX(b), y2: H - 8, stroke: "var(--viz-warn)", strokeWidth: "1.5", strokeDasharray: "3 3" }),
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: toX(a), cy: H - 8, r: 6, fill: "var(--viz-warn)", stroke: "var(--bg)", strokeWidth: "2" }),
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: toX(b), cy: H - 8, r: 6, fill: "var(--viz-warn)", stroke: "var(--bg)", strokeWidth: "2" })
                ] })
              ]
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 240, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Parameters" }),
            dist === "normal" && /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03BC", min: -3, max: 3, step: 0.05, value: s.mu, onChange: (v) => setParam("mu", v) }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03C3", min: 0.1, max: 3, step: 0.05, value: s.sigma, onChange: (v) => setParam("sigma", v) })
            ] }),
            dist === "beta" && /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B1", min: 0.5, max: 10, step: 0.1, value: s.alpha, onChange: (v) => setParam("alpha", v) }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B2", min: 0.5, max: 10, step: 0.1, value: s.beta, onChange: (v) => setParam("beta", v) })
            ] }),
            dist === "gamma" && /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "k", min: 0.5, max: 8, step: 0.1, value: s.k, onChange: (v) => setParam("k", v) }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B8", min: 0.2, max: 3, step: 0.05, value: s.theta, onChange: (v) => setParam("theta", v) })
            ] }),
            dist === "exponential" && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03BB", min: 0.2, max: 4, step: 0.05, value: s.lambda, onChange: (v) => setParam("lambda", v) }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 14 }, children: "View" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              Tabs,
              {
                value: view,
                onChange: (id) => setView(id),
                items: [
                  { id: "pdf", label: "PDF" },
                  { id: "cdf", label: "CDF" }
                ]
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(ToggleRow, { checked: logY, onChange: setLogY, children: "log y-axis (PDF)" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, marginTop: 12 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setHist((h) => [...h, 1]), children: "Resample" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setS(DEFAULTS), children: "Reset params" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Beta(\u03B1,\u03B2) supports only [0,1] and shapes wildly with the two parameters. Gamma generalises Exponential (k=1). Resample to see how histogram noise settles toward the true PDF as N grows."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<DistributionExplorer />);
