// generated by @readrun/widgets — edit .readrun/widgets/force-graph.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/force-graph.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// src/figura/math/force.ts
function forceStep(nodes, edges, cfg) {
  const repulsion = cfg.repulsion ?? 4500;
  const springK = cfg.springK ?? 0.04;
  const springRest = cfg.springRest ?? 70;
  const damping = cfg.damping ?? 0.85;
  const centerPull = cfg.centerPull ?? 5e-3;
  const dt = cfg.dt ?? 1;
  const cx = cfg.width / 2;
  const cy = cfg.height / 2;
  for (let i = 0; i < nodes.length; i++) {
    const ni = nodes[i];
    if (ni.fixed) continue;
    let fx = 0;
    let fy = 0;
    for (let j = 0; j < nodes.length; j++) {
      if (i === j) continue;
      const nj = nodes[j];
      const dx = ni.x - nj.x;
      const dy = ni.y - nj.y;
      const d2 = dx * dx + dy * dy + 0.01;
      const f = repulsion / d2;
      const d = Math.sqrt(d2);
      fx += dx / d * f;
      fy += dy / d * f;
    }
    fx += (cx - ni.x) * centerPull;
    fy += (cy - ni.y) * centerPull;
    ni.vx = (ni.vx + fx * dt) * damping;
    ni.vy = (ni.vy + fy * dt) * damping;
  }
  for (const e of edges) {
    const a = nodes[e.s];
    const b = nodes[e.t];
    if (!a || !b) continue;
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const d = Math.hypot(dx, dy) + 0.01;
    const f = springK * (d - springRest);
    const fx = dx / d * f;
    const fy = dy / d * f;
    if (!a.fixed) {
      a.vx += fx * dt;
      a.vy += fy * dt;
    }
    if (!b.fixed) {
      b.vx -= fx * dt;
      b.vy -= fy * dt;
    }
  }
  for (const n of nodes) {
    if (n.fixed) continue;
    n.x += n.vx * dt;
    n.y += n.vy * dt;
    const m = 24;
    if (n.x < m) {
      n.x = m;
      n.vx *= -0.4;
    }
    if (n.x > cfg.width - m) {
      n.x = cfg.width - m;
      n.vx *= -0.4;
    }
    if (n.y < m) {
      n.y = m;
      n.vy *= -0.4;
    }
    if (n.y > cfg.height - m) {
      n.y = cfg.height - m;
      n.vy *= -0.4;
    }
  }
}
function makeRandomGraph(n, edgeProb, width, height, seed = 1) {
  let s = seed >>> 0;
  const rng = () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
  const nodes = [];
  for (let i = 0; i < n; i++) {
    nodes.push({
      id: i,
      x: width / 2 + (rng() - 0.5) * 200,
      y: height / 2 + (rng() - 0.5) * 200,
      vx: 0,
      vy: 0
    });
  }
  const edges = [];
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      if (rng() < edgeProb) edges.push({ s: i, t: j });
    }
  }
  return { nodes, edges };
}
function makeRingGraph(n, width, height) {
  const nodes = [];
  const cx = width / 2;
  const cy = height / 2;
  const r = Math.min(width, height) * 0.32;
  for (let i = 0; i < n; i++) {
    const a = i / n * Math.PI * 2;
    nodes.push({ id: i, x: cx + Math.cos(a) * r, y: cy + Math.sin(a) * r, vx: 0, vy: 0 });
  }
  const edges = [];
  for (let i = 0; i < n; i++) edges.push({ s: i, t: (i + 1) % n });
  return { nodes, edges };
}
function makeSmallWorld(n, rewireProb, width, height, seed = 1) {
  let s = seed >>> 0;
  const rng = () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
  const { nodes, edges } = makeRingGraph(n, width, height);
  for (let i = 0; i < n; i++) edges.push({ s: i, t: (i + 2) % n });
  for (const e of edges) {
    if (rng() < rewireProb) {
      let nt = Math.floor(rng() * n);
      if (nt === e.s) nt = (nt + 1) % n;
      e.t = nt;
    }
  }
  return { nodes, edges };
}
function makeScaleFree(n, width, height, seed = 1) {
  let s = seed >>> 0;
  const rng = () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
  const nodes = [];
  for (let i = 0; i < n; i++) {
    nodes.push({
      id: i,
      x: width / 2 + (rng() - 0.5) * 200,
      y: height / 2 + (rng() - 0.5) * 200,
      vx: 0,
      vy: 0
    });
  }
  const edges = [];
  edges.push({ s: 0, t: 1 });
  edges.push({ s: 1, t: 2 });
  edges.push({ s: 2, t: 0 });
  const degree = new Array(n).fill(0);
  degree[0] = 2;
  degree[1] = 2;
  degree[2] = 2;
  for (let i = 3; i < n; i++) {
    const totalDeg = degree.reduce((a, b) => a + b, 0);
    const targets = /* @__PURE__ */ new Set();
    while (targets.size < Math.min(2, i)) {
      let r = rng() * totalDeg;
      for (let j = 0; j < i; j++) {
        r -= degree[j];
        if (r <= 0) {
          targets.add(j);
          break;
        }
      }
    }
    for (const t of targets) {
      edges.push({ s: i, t });
      degree[i]++;
      degree[t]++;
    }
  }
  return { nodes, edges };
}
function degreeOf(nodes, edges) {
  const d = new Array(nodes.length).fill(0);
  for (const e of edges) {
    d[e.s]++;
    d[e.t]++;
  }
  return d;
}

// readrun-docs/.readrun/widgets/force-graph.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var TOPOS = [
  { id: "random", label: "Random" },
  { id: "ring", label: "Ring" },
  { id: "smallWorld", label: "Small-world" },
  { id: "scaleFree", label: "Scale-free" }
];
function ForceGraph() {
  const W = 540;
  const H = 420;
  const [topo, setTopo] = (0, import_react4.useState)("scaleFree");
  const [n, setN] = (0, import_react4.useState)(28);
  const [seed, setSeed] = (0, import_react4.useState)(7);
  const [freeze, setFreeze] = (0, import_react4.useState)(false);
  const [hover, setHover] = (0, import_react4.useState)(null);
  const [, force] = (0, import_react4.useState)(0);
  const stateRef = (0, import_react4.useRef)({ nodes: [], edges: [] });
  const dragRef = (0, import_react4.useRef)({ id: null, offX: 0, offY: 0 });
  const svgRef = (0, import_react4.useRef)(null);
  const rafRef = (0, import_react4.useRef)(0);
  (0, import_react4.useEffect)(() => {
    let g;
    if (topo === "random") g = makeRandomGraph(n, 0.12, W, H, seed);
    else if (topo === "ring") g = makeRingGraph(n, W, H);
    else if (topo === "smallWorld") g = makeSmallWorld(n, 0.15, W, H, seed);
    else g = makeScaleFree(n, W, H, seed);
    stateRef.current = g;
    force((x) => x + 1);
  }, [topo, n, seed]);
  (0, import_react4.useEffect)(() => {
    if (freeze) return;
    const tick = () => {
      forceStep(stateRef.current.nodes, stateRef.current.edges, { width: W, height: H });
      force((x) => x + 1);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [freeze]);
  const degree = degreeOf(stateRef.current.nodes, stateRef.current.edges);
  const maxDeg = Math.max(...degree, 1);
  const histBins = 10;
  const hist = new Array(histBins).fill(0);
  for (const d of degree) {
    const i = Math.min(histBins - 1, Math.floor(d / (maxDeg + 1) * histBins));
    hist[i]++;
  }
  const histMax = Math.max(...hist, 1);
  function pos(e) {
    const rect = svgRef.current.getBoundingClientRect();
    return [(e.clientX - rect.left) * (W / rect.width), (e.clientY - rect.top) * (H / rect.height)];
  }
  function down(e) {
    const [x, y] = pos(e);
    let best = -1;
    let bd = 30;
    for (const node of stateRef.current.nodes) {
      const d = Math.hypot(node.x - x, node.y - y);
      if (d < bd) {
        bd = d;
        best = node.id;
      }
    }
    if (best >= 0) {
      dragRef.current = { id: best, offX: stateRef.current.nodes[best].x - x, offY: stateRef.current.nodes[best].y - y };
      stateRef.current.nodes[best].fixed = true;
    }
  }
  function move(e) {
    const [x, y] = pos(e);
    if (dragRef.current.id !== null) {
      const node = stateRef.current.nodes[dragRef.current.id];
      if (node) {
        node.x = x + dragRef.current.offX;
        node.y = y + dragRef.current.offY;
        node.vx = 0;
        node.vy = 0;
      }
      return;
    }
    let h = null;
    let bd = 24;
    for (const node of stateRef.current.nodes) {
      const d = Math.hypot(node.x - x, node.y - y);
      if (d < bd) {
        bd = d;
        h = node.id;
      }
    }
    setHover(h);
  }
  function up() {
    if (dragRef.current.id !== null) {
      const node = stateRef.current.nodes[dragRef.current.id];
      if (node) node.fixed = false;
    }
    dragRef.current.id = null;
  }
  const highlightSet = (0, import_react4.useMemo)(() => {
    if (hover === null) return /* @__PURE__ */ new Set();
    const s = /* @__PURE__ */ new Set([hover]);
    for (const e of stateRef.current.edges) {
      if (e.s === hover) s.add(e.t);
      if (e.t === hover) s.add(e.s);
    }
    return s;
  }, [hover]);
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Force-Directed Graph",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "nodes", value: stateRef.current.nodes.length }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "edges", value: stateRef.current.edges.length }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "max deg", value: maxDeg, color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Four classic topologies. Drag a node to fix it (and let the rest settle around it). Hover to highlight neighbours; the histogram on the right shows the degree distribution." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Tabs, { value: topo, onChange: (id) => setTopo(id), items: TOPOS }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
            "svg",
            {
              ref: svgRef,
              viewBox: `0 0 ${W} ${H}`,
              width: W,
              height: H,
              style: { display: "block", maxWidth: "100%", touchAction: "none" },
              onPointerDown: down,
              onPointerMove: move,
              onPointerUp: up,
              onPointerLeave: up,
              children: [
                stateRef.current.edges.map((e, i) => {
                  const a = stateRef.current.nodes[e.s];
                  const b = stateRef.current.nodes[e.t];
                  if (!a || !b) return null;
                  const dim = hover !== null && !(highlightSet.has(e.s) && highlightSet.has(e.t));
                  return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                    "line",
                    {
                      x1: a.x,
                      y1: a.y,
                      x2: b.x,
                      y2: b.y,
                      stroke: "var(--viz-axis)",
                      strokeWidth: dim ? 0.6 : 1.2,
                      opacity: dim ? 0.18 : 0.7
                    },
                    i
                  );
                }),
                stateRef.current.nodes.map((node) => {
                  const d = degree[node.id];
                  const r = 4 + d / (maxDeg + 1) * 8;
                  const isHover = hover === node.id;
                  const inHL = highlightSet.has(node.id);
                  const fill = hover !== null && !inHL ? "var(--text-muted)" : "var(--viz-trace)";
                  return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                    "circle",
                    {
                      cx: node.x,
                      cy: node.y,
                      r,
                      fill,
                      stroke: "var(--bg)",
                      strokeWidth: isHover ? 2.5 : 1.5,
                      opacity: hover !== null && !inHL ? 0.35 : 1,
                      style: { cursor: "grab" }
                    },
                    node.id
                  );
                })
              ]
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Controls" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setSeed((s) => s + 1), children: "Regenerate" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setFreeze((f) => !f), children: freeze ? "Unfreeze" : "Freeze" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12 }, children: [12, 20, 28, 40, 60].map((v) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", active: n === v, onClick: () => setN(v), children: v }, v)) }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Degree distribution" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("svg", { viewBox: "0 0 200 80", width: "100%", height: 80, style: { display: "block" }, children: [
              hist.map((c, i) => {
                const bw = 200 / histBins;
                const h = c / histMax * 70;
                return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("rect", { x: i * bw + 2, y: 75 - h, width: bw - 4, height: h, fill: "var(--viz-warn)" }, i);
              }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: 75, x2: 200, y2: 75, stroke: "var(--viz-axis)", strokeWidth: "1" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Random graphs have Poisson-shaped degree distributions. Scale-free graphs (preferential attachment) produce hubs \u2014 a long-tailed distribution visible in the histogram. Small-world keeps short paths despite local clustering."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<ForceGraph />);
