// generated by @readrun/widgets — edit .readrun/widgets/fourier-builder.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/fourier-builder.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/fourier-builder.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var TARGETS = [
  { id: "square", label: "Square" },
  { id: "saw", label: "Sawtooth" },
  { id: "triangle", label: "Triangle" }
];
function targetCoef(target, n) {
  if (target === "square") {
    if (n % 2 === 0) return 0;
    return 4 / Math.PI / n;
  }
  if (target === "saw") {
    return (n % 2 === 0 ? -1 : 1) * 2 / (Math.PI * n);
  }
  if (n % 2 === 0) return 0;
  const k = (n - 1) / 2;
  return (k % 2 === 0 ? 1 : -1) * 8 / (Math.PI * Math.PI * n * n);
}
function FourierBuilder() {
  const W = 620;
  const H = 320;
  const [target, setTarget] = (0, import_react4.useState)("square");
  const [terms, setTerms] = (0, import_react4.useState)(5);
  const N = 600;
  const points = [];
  for (let i = 0; i < N; i++) {
    const x = i / (N - 1) * 2 * Math.PI;
    let y = 0;
    for (let n = 1; n <= terms; n++) {
      y += targetCoef(target, n) * Math.sin(n * x);
    }
    points.push([x, y]);
  }
  const yMax = Math.max(...points.map(([, y]) => Math.abs(y))) * 1.15 || 1.2;
  const toX = (x) => x / (2 * Math.PI) * W;
  const toY = (y) => H / 2 - y / yMax * (H * 0.42);
  const truth = [];
  for (let i = 0; i < N; i++) {
    const x = i / (N - 1) * 2 * Math.PI;
    let y = 0;
    if (target === "square") y = x < Math.PI ? 1 : -1;
    else if (target === "saw") y = 1 - x / Math.PI;
    else y = 1 - 4 * Math.abs(x / (2 * Math.PI) - 0.5);
    truth.push([x, y]);
  }
  const harmonics = [];
  for (let n = 1; n <= terms; n++) {
    const c = targetCoef(target, n);
    if (c !== 0) harmonics.push({ n, coef: c });
  }
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Fourier Builder",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "target", value: target, color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "terms", value: terms })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Add sine harmonics to approximate a target waveform. The faint dashed line is the true target; the bold curve is the Fourier sum. Watch Gibbs phenomenon (overshoot at the discontinuity) refuse to vanish even at high N." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", gap: 8, marginBottom: 8 }, children: TARGETS.map((t) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", active: target === t.id, onClick: () => setTarget(t.id), children: t.label }, t.id)) }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H / 2, x2: W, y2: H / 2, stroke: "var(--viz-axis)", strokeWidth: "1", opacity: "0.5" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polyline",
              {
                points: truth.map(([x, y]) => `${toX(x)},${toY(y)}`).join(" "),
                fill: "none",
                stroke: "var(--viz-axis)",
                strokeWidth: "1.5",
                strokeDasharray: "6 5",
                opacity: "0.7"
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polyline",
              {
                points: points.map(([x, y]) => `${toX(x)},${toY(y)}`).join(" "),
                fill: "none",
                stroke: "var(--viz-trace)",
                strokeWidth: "2.6"
              }
            ),
            harmonics.slice(0, 6).map(({ n, coef }, i) => {
              const pts = [];
              for (let j = 0; j < N; j++) {
                const x = j / (N - 1) * 2 * Math.PI;
                const y = coef * Math.sin(n * x);
                pts.push(`${toX(x)},${toY(y)}`);
              }
              return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                "polyline",
                {
                  points: pts.join(" "),
                  fill: "none",
                  stroke: "var(--viz-warn)",
                  strokeWidth: "0.8",
                  opacity: 0.3 - i * 0.04
                },
                n
              );
            })
          ] }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Harmonics" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "terms", min: 1, max: 40, step: 1, value: terms, onChange: setTerms, format: (v) => `${v}` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 14 }, children: "Coefficients" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", flexDirection: "column", gap: 4, fontSize: 11, fontFamily: "var(--font-mono, monospace)", color: "var(--text-muted)", maxHeight: 160, overflowY: "auto" }, children: harmonics.map(({ n, coef }) => /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { children: [
              "a",
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("sub", { children: n }),
              " = ",
              coef.toFixed(4)
            ] }, n)) }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Square waves use only odd harmonics with 1/n coefficients. Triangles fall off as 1/n\xB2 \u2014 much faster, no Gibbs. Bump the term count to 40 and the discontinuity overshoot stays at ~9% \u2014 that's Gibbs."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<FourierBuilder />);
