// generated by @readrun/widgets — edit .readrun/widgets/git-graph-explorer.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/git-graph-explorer.tsx
var import_react5 = __toESM(require_react(), 1);

// src/figura/diagram/Flow.tsx
var import_react = __toESM(require_react(), 1);

// src/figura/diagram/layout/dag.ts
function dag(nodes, edges, opts) {
  const rankSep = opts?.rankSeparation ?? 120;
  const nodeSep = opts?.nodeSeparation ?? 40;
  const defW = opts?.defaultWidth ?? 100;
  const defH = opts?.defaultHeight ?? 50;
  if (nodes.length === 0) return [];
  const nodeIds = new Set(nodes.map((n) => n.id));
  const outEdges = /* @__PURE__ */ new Map();
  const inDegree = /* @__PURE__ */ new Map();
  const edgeByTo = /* @__PURE__ */ new Map();
  for (const n of nodes) {
    outEdges.set(n.id, []);
    inDegree.set(n.id, 0);
  }
  for (const e of edges) {
    if (!nodeIds.has(e.from) || !nodeIds.has(e.to)) continue;
    outEdges.get(e.from).push(e.to);
    inDegree.set(e.to, (inDegree.get(e.to) ?? 0) + 1);
    if (!edgeByTo.has(e.to)) edgeByTo.set(e.to, e);
  }
  const rank = /* @__PURE__ */ new Map();
  const queue = [];
  for (const n of nodes) {
    if ((inDegree.get(n.id) ?? 0) === 0) {
      queue.push(n.id);
      rank.set(n.id, 0);
    }
  }
  const sorted = [];
  while (queue.length > 0) {
    queue.sort();
    const id = queue.shift();
    sorted.push(id);
    for (const childId of outEdges.get(id) ?? []) {
      const newRank = (rank.get(id) ?? 0) + 1;
      if (!rank.has(childId) || rank.get(childId) < newRank) {
        rank.set(childId, newRank);
      }
      const newIn = (inDegree.get(childId) ?? 0) - 1;
      inDegree.set(childId, newIn);
      if (newIn === 0) {
        queue.push(childId);
      }
    }
  }
  if (sorted.length !== nodes.length) {
    for (const e of edges) {
      if ((rank.get(e.from) ?? -1) >= (rank.get(e.to) ?? -1) && sorted.includes(e.from)) {
      }
    }
    const unprocessed = new Set(nodes.map((n) => n.id).filter((id) => !sorted.includes(id)));
    for (const e of edges) {
      if (unprocessed.has(e.to) || unprocessed.has(e.from)) {
        throw new Error(
          `dag layout: cycle detected. Edge "${e.id}" (${e.from} \u2192 ${e.to}) is part of a cycle.`
        );
      }
    }
    throw new Error("dag layout: cycle detected in the graph.");
  }
  const rankGroups = /* @__PURE__ */ new Map();
  for (const [id, r] of rank.entries()) {
    if (!rankGroups.has(r)) rankGroups.set(r, []);
    rankGroups.get(r).push(id);
  }
  for (const group of rankGroups.values()) {
    group.sort();
  }
  const nodeById = new Map(nodes.map((n) => [n.id, n]));
  const positioned = /* @__PURE__ */ new Map();
  for (const [r, group] of rankGroups.entries()) {
    const n = group.length;
    const totalWidth = n * defW + (n - 1) * nodeSep;
    const startX = -totalWidth / 2 + defW / 2;
    for (let i = 0; i < group.length; i++) {
      const id = group[i];
      const node = nodeById.get(id);
      const w = node.width ?? defW;
      const h = node.height ?? defH;
      positioned.set(id, {
        ...node,
        x: startX + i * (defW + nodeSep),
        y: r * rankSep,
        width: w,
        height: h
      });
    }
  }
  return nodes.map((n) => positioned.get(n.id));
}

// src/figura/diagram/layout/tree.ts
function tree(rootNode, childrenOf, opts) {
  const levelSep = opts?.levelSeparation ?? 100;
  const siblingSep = opts?.siblingSeparation ?? 40;
  const defW = opts?.defaultWidth ?? 100;
  const defH = opts?.defaultHeight ?? 50;
  const nextX = /* @__PURE__ */ new Map();
  function buildTree(node, depth) {
    const children = childrenOf(node).map((c) => buildTree(c, depth + 1));
    const internal = {
      source: node,
      children,
      depth,
      x: 0,
      y: depth * levelSep
    };
    if (children.length === 0) {
      const cur = nextX.get(depth) ?? 0;
      internal.x = cur;
      nextX.set(depth, cur + defW + siblingSep);
    } else {
      const leftX = children[0].x;
      const rightX = children[children.length - 1].x;
      internal.x = (leftX + rightX) / 2;
      const cur = nextX.get(depth) ?? 0;
      if (internal.x + defW / 2 > cur) {
        nextX.set(depth, internal.x + defW + siblingSep);
      }
    }
    return internal;
  }
  const root = buildTree(rootNode, 0);
  const result = [];
  function collect(n) {
    const node = n.source;
    result.push({
      ...node,
      x: n.x,
      y: n.y,
      width: node.width ?? defW,
      height: node.height ?? defH
    });
    for (const c of n.children) collect(c);
  }
  collect(root);
  return result;
}

// src/figura/math/force.ts
function forceStep(nodes, edges, cfg) {
  const repulsion = cfg.repulsion ?? 4500;
  const springK = cfg.springK ?? 0.04;
  const springRest = cfg.springRest ?? 70;
  const damping = cfg.damping ?? 0.85;
  const centerPull = cfg.centerPull ?? 5e-3;
  const dt = cfg.dt ?? 1;
  const cx = cfg.width / 2;
  const cy = cfg.height / 2;
  for (let i = 0; i < nodes.length; i++) {
    const ni = nodes[i];
    if (ni.fixed) continue;
    let fx = 0;
    let fy = 0;
    for (let j = 0; j < nodes.length; j++) {
      if (i === j) continue;
      const nj = nodes[j];
      const dx = ni.x - nj.x;
      const dy = ni.y - nj.y;
      const d2 = dx * dx + dy * dy + 0.01;
      const f = repulsion / d2;
      const d = Math.sqrt(d2);
      fx += dx / d * f;
      fy += dy / d * f;
    }
    fx += (cx - ni.x) * centerPull;
    fy += (cy - ni.y) * centerPull;
    ni.vx = (ni.vx + fx * dt) * damping;
    ni.vy = (ni.vy + fy * dt) * damping;
  }
  for (const e of edges) {
    const a = nodes[e.s];
    const b = nodes[e.t];
    if (!a || !b) continue;
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const d = Math.hypot(dx, dy) + 0.01;
    const f = springK * (d - springRest);
    const fx = dx / d * f;
    const fy = dy / d * f;
    if (!a.fixed) {
      a.vx += fx * dt;
      a.vy += fy * dt;
    }
    if (!b.fixed) {
      b.vx -= fx * dt;
      b.vy -= fy * dt;
    }
  }
  for (const n of nodes) {
    if (n.fixed) continue;
    n.x += n.vx * dt;
    n.y += n.vy * dt;
    const m = 24;
    if (n.x < m) {
      n.x = m;
      n.vx *= -0.4;
    }
    if (n.x > cfg.width - m) {
      n.x = cfg.width - m;
      n.vx *= -0.4;
    }
    if (n.y < m) {
      n.y = m;
      n.vy *= -0.4;
    }
    if (n.y > cfg.height - m) {
      n.y = cfg.height - m;
      n.vy *= -0.4;
    }
  }
}

// src/figura/math/random.ts
function mulberry32(seed) {
  let s = seed >>> 0;
  return () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

// src/figura/diagram/layout/force.ts
function force(nodes, edges, opts) {
  if (nodes.length === 0) return [];
  const iterations = opts?.iterations ?? 300;
  const width = opts?.width ?? 800;
  const height = opts?.height ?? 600;
  const seed = opts?.seed ?? 1;
  const defW = opts?.defaultWidth ?? 100;
  const defH = opts?.defaultHeight ?? 50;
  const rng = mulberry32(seed);
  const indexById = new Map(nodes.map((n, i) => [n.id, i]));
  const forceNodes = nodes.map((_n, i) => ({
    id: i,
    x: width / 2 + (rng() - 0.5) * 200,
    y: height / 2 + (rng() - 0.5) * 200,
    vx: 0,
    vy: 0
  }));
  const forceEdges = edges.map((e) => {
    const s = indexById.get(e.from);
    const t = indexById.get(e.to);
    if (s === void 0 || t === void 0) return null;
    return { s, t };
  }).filter((e) => e !== null);
  const cfg = { width, height };
  for (let i = 0; i < iterations; i++) {
    forceStep(forceNodes, forceEdges, cfg);
  }
  return nodes.map((node, i) => ({
    ...node,
    x: forceNodes[i].x,
    y: forceNodes[i].y,
    width: node.width ?? defW,
    height: node.height ?? defH
  }));
}

// src/figura/diagram/edge/ports.ts
function nodePorts(node) {
  const { x: cx, y: cy, width, height } = node;
  const w2 = width / 2;
  const h2 = height / 2;
  return {
    top: { x: cx, y: cy - h2, dir: { dx: 0, dy: -1 } },
    right: { x: cx + w2, y: cy, dir: { dx: 1, dy: 0 } },
    bottom: { x: cx, y: cy + h2, dir: { dx: 0, dy: 1 } },
    left: { x: cx - w2, y: cy, dir: { dx: -1, dy: 0 } }
  };
}
function selectPort(ports, targetVec, exclude) {
  const len = Math.hypot(targetVec.x, targetVec.y) || 1;
  const tx = targetVec.x / len;
  const ty = targetVec.y / len;
  const ranked = Object.keys(ports).map((name) => ({
    name,
    port: ports[name],
    score: ports[name].dir.dx * tx + ports[name].dir.dy * ty
  })).sort((a, b) => b.score - a.score);
  if (exclude && exclude.size > 0) {
    const free = ranked.find((r) => !exclude.has(r.name));
    if (free) return { name: free.name, port: free.port };
  }
  const top = ranked[0];
  return { name: top.name, port: top.port };
}
function selectEdgePorts(fromNode, toNode, opts) {
  const dx = toNode.x - fromNode.x;
  const dy = toNode.y - fromNode.y;
  const fromPorts = nodePorts(fromNode);
  const toPorts = nodePorts(toNode);
  const fromSel = selectPort(fromPorts, { x: dx, y: dy }, opts?.excludeFrom);
  const toSel = selectPort(toPorts, { x: -dx, y: -dy }, opts?.excludeTo);
  return { from: fromSel.port, to: toSel.port, fromName: fromSel.name, toName: toSel.name };
}

// src/figura/diagram/edge/router.ts
function straightWithPorts(from, to) {
  return `M ${num(from.x)} ${num(from.y)} L ${num(to.x)} ${num(to.y)}`;
}
function curveWithPorts(from, to) {
  const dist = Math.hypot(to.x - from.x, to.y - from.y);
  const offset = Math.max(20, 0.4 * dist);
  const c1x = from.x + from.dir.dx * offset;
  const c1y = from.y + from.dir.dy * offset;
  const c2x = to.x + to.dir.dx * offset;
  const c2y = to.y + to.dir.dy * offset;
  return `M ${num(from.x)} ${num(from.y)} C ${num(c1x)} ${num(c1y)} ${num(c2x)} ${num(c2y)} ${num(to.x)} ${num(to.y)}`;
}
function orthogonalWithPorts(from, to, opts) {
  const buffer = opts?.buffer ?? 20;
  const sx = from.x;
  const sy = from.y;
  const tx = to.x;
  const ty = to.y;
  const sgx = sx + from.dir.dx * buffer;
  const sgy = sy + from.dir.dy * buffer;
  const tgx = tx + to.dir.dx * buffer;
  const tgy = ty + to.dir.dy * buffer;
  const srcHoriz = from.dir.dx !== 0;
  const tgtHoriz = to.dir.dx !== 0;
  let mid;
  if (srcHoriz && tgtHoriz) {
    const midX = (sgx + tgx) / 2;
    mid = `L ${num(midX)} ${num(sgy)} L ${num(midX)} ${num(tgy)}`;
  } else if (!srcHoriz && !tgtHoriz) {
    const midY = (sgy + tgy) / 2;
    mid = `L ${num(sgx)} ${num(midY)} L ${num(tgx)} ${num(midY)}`;
  } else if (srcHoriz && !tgtHoriz) {
    mid = `L ${num(tgx)} ${num(sgy)}`;
  } else {
    mid = `L ${num(sgx)} ${num(tgy)}`;
  }
  return `M ${num(sx)} ${num(sy)} L ${num(sgx)} ${num(sgy)} ${mid} L ${num(tgx)} ${num(tgy)} L ${num(tx)} ${num(ty)}`;
}
function num(n) {
  return n.toFixed(2).replace(/\.?0+$/, "");
}

// src/figura/diagram/Flow.tsx
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
var ARROW_ID = "figura-flow-arrow";
var DEF_W = 100;
var DEF_H = 50;
var NODE_FILL = "var(--bg, #ffffff)";
var NODE_STROKE = "var(--text, #1f2328)";
var EDGE_STROKE = "var(--text-muted, #656d76)";
var INNER_DX_FACTOR = 0.5;
var INNER_DY = 20;
function clientToSvg(svg, clientX, clientY) {
  const ctm = svg.getScreenCTM();
  if (!ctm) return null;
  const inv = ctm.inverse();
  const pt = svg.createSVGPoint();
  pt.x = clientX;
  pt.y = clientY;
  const local = pt.matrixTransform(inv);
  return { x: local.x, y: local.y };
}
function NodeShape({
  shape,
  w,
  h
}) {
  const sharedProps = {
    fill: NODE_FILL,
    stroke: NODE_STROKE,
    strokeWidth: 1
  };
  if (shape === "circle") {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "circle",
      {
        cx: w / 2,
        cy: h / 2,
        r: Math.min(w, h) / 2,
        ...sharedProps
      }
    );
  }
  if (shape === "ellipse") {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "ellipse",
      {
        cx: w / 2,
        cy: h / 2,
        rx: w / 2,
        ry: h / 2,
        ...sharedProps
      }
    );
  }
  if (shape === "diamond") {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "polygon",
      {
        points: `${w / 2},0 ${w},${h / 2} ${w / 2},${h} 0,${h / 2}`,
        ...sharedProps
      }
    );
  }
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "rect",
    {
      width: w,
      height: h,
      x: 0,
      y: 0,
      ...sharedProps,
      rx: 0
    }
  );
}
function DraggableNode({
  node,
  svgRef,
  innerDx,
  innerDy,
  view,
  onClick,
  onHover,
  onDragMove,
  draggable
}) {
  const offsetRef = import_react.default.useRef(null);
  const movedRef = import_react.default.useRef(false);
  const onPointerDown = (e) => {
    if (!draggable || !svgRef.current) return;
    e.stopPropagation();
    e.preventDefault();
    e.currentTarget.setPointerCapture(e.pointerId);
    const pt = clientToSvg(svgRef.current, e.clientX, e.clientY);
    if (!pt) return;
    const innerX = (pt.x - innerDx - view.panX) / view.zoom;
    const innerY = (pt.y - innerDy - view.panY) / view.zoom;
    offsetRef.current = { ox: innerX - node.x, oy: innerY - node.y };
    movedRef.current = false;
  };
  const onPointerMove = (e) => {
    if (!offsetRef.current || !svgRef.current) return;
    const pt = clientToSvg(svgRef.current, e.clientX, e.clientY);
    if (!pt) return;
    const innerX = (pt.x - innerDx - view.panX) / view.zoom;
    const innerY = (pt.y - innerDy - view.panY) / view.zoom;
    onDragMove(innerX - offsetRef.current.ox, innerY - offsetRef.current.oy);
    movedRef.current = true;
  };
  const onPointerUp = (e) => {
    if (e.currentTarget.hasPointerCapture(e.pointerId)) {
      e.currentTarget.releasePointerCapture(e.pointerId);
    }
    offsetRef.current = null;
    if (!movedRef.current && onClick) {
      onClick(node);
    }
  };
  const isDragging = offsetRef.current !== null;
  const { x, y, width, height, id } = node;
  const label = typeof node["label"] === "string" ? node["label"] : id;
  const shape = node.shape ?? "rect";
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "g",
    {
      transform: `translate(${x - width / 2}, ${y - height / 2})`,
      style: {
        cursor: draggable ? isDragging ? "grabbing" : "grab" : onClick ? "pointer" : "default",
        touchAction: "none"
      },
      onPointerDown,
      onPointerMove,
      onPointerUp,
      onPointerCancel: onPointerUp,
      onMouseEnter: onHover ? () => onHover(node) : void 0,
      onMouseLeave: onHover ? () => onHover(null) : void 0,
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(NodeShape, { shape, w: width, h: height }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          "text",
          {
            x: width / 2,
            y: height / 2,
            dominantBaseline: "middle",
            textAnchor: "middle",
            fontSize: 11,
            fill: "var(--text, #1f2328)",
            fontFamily: "var(--font-body, ui-sans-serif, system-ui, sans-serif)",
            style: { userSelect: "none", pointerEvents: "none" },
            children: label
          }
        )
      ]
    }
  );
}
function defaultRenderEdge(pathStr, edge2) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "path",
    {
      d: pathStr,
      stroke: EDGE_STROKE,
      strokeWidth: 1.5,
      fill: "none",
      markerEnd: `url(#${ARROW_ID})`
    },
    edge2.id
  );
}
function pathFromPorts(router, from, to) {
  switch (router) {
    case "straight":
      return straightWithPorts(from, to);
    case "curve":
      return curveWithPorts(from, to);
    case "orthogonal":
    default:
      return orthogonalWithPorts(from, to);
  }
}
function Flow({
  nodes,
  edges,
  layout: layoutMode,
  childrenOf,
  rootId,
  edgeRouter,
  renderNode,
  renderEdge,
  width,
  height,
  onNodeClick,
  onNodeHover,
  draggable = true
}) {
  const svgRef = import_react.default.useRef(null);
  const innerDx = width * INNER_DX_FACTOR;
  const innerDy = INNER_DY;
  const [overrides, setOverrides] = import_react.default.useState({});
  const [view, setView] = import_react.default.useState({
    panX: 0,
    panY: 0,
    zoom: 1
  });
  const panStateRef = import_react.default.useRef({ active: false, startClientX: 0, startClientY: 0, startPanX: 0, startPanY: 0 });
  const updateOverride = import_react.default.useCallback((id, x, y) => {
    setOverrides((prev) => ({ ...prev, [id]: { x, y } }));
  }, []);
  let positioned;
  if (layoutMode === "manual") {
    positioned = nodes.map((n) => ({
      ...n,
      x: n.x ?? 0,
      y: n.y ?? 0,
      width: n.width ?? DEF_W,
      height: n.height ?? DEF_H
    }));
  } else if (layoutMode === "dag") {
    positioned = dag(nodes, edges);
  } else if (layoutMode === "tree") {
    const root = nodes.find((n) => n.id === rootId);
    if (!root) {
      const fallbackRoot = nodes[0];
      positioned = fallbackRoot ? tree(fallbackRoot, childrenOf ?? (() => []), {
        levelSeparation: height / Math.max(4, nodes.length)
      }) : [];
    } else {
      positioned = tree(root, childrenOf ?? (() => []), {
        levelSeparation: height / Math.max(4, nodes.length)
      });
    }
  } else {
    positioned = force(nodes, edges, { width, height });
  }
  positioned = positioned.map((n) => {
    const o = overrides[n.id];
    return o ? { ...n, x: o.x, y: o.y } : n;
  });
  const posById = new Map(positioned.map((n) => [n.id, n]));
  const router = edgeRouter ?? (layoutMode === "force" ? "curve" : layoutMode === "manual" ? "straight" : "orthogonal");
  const usedPorts = /* @__PURE__ */ new Map();
  const edgeElements = edges.map((e) => {
    const fromNode = posById.get(e.from);
    const toNode = posById.get(e.to);
    if (!fromNode || !toNode) return null;
    const fromUsed = usedPorts.get(e.from) ?? /* @__PURE__ */ new Set();
    const toUsed = usedPorts.get(e.to) ?? /* @__PURE__ */ new Set();
    const { from, to, fromName, toName } = selectEdgePorts(fromNode, toNode, {
      excludeFrom: fromUsed,
      excludeTo: toUsed
    });
    fromUsed.add(fromName);
    toUsed.add(toName);
    usedPorts.set(e.from, fromUsed);
    usedPorts.set(e.to, toUsed);
    const pathStr = pathFromPorts(router, from, to);
    if (renderEdge) {
      return renderEdge(pathStr, e, fromNode, toNode);
    }
    return defaultRenderEdge(pathStr, e);
  }).filter(Boolean);
  const nodeElements = positioned.map((n) => {
    if (renderNode) return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_react.default.Fragment, { children: renderNode(n) }, n.id);
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      DraggableNode,
      {
        node: n,
        svgRef,
        innerDx,
        innerDy,
        view,
        draggable,
        onClick: onNodeClick,
        onHover: onNodeHover,
        onDragMove: (x, y) => updateOverride(n.id, x, y)
      },
      n.id
    );
  });
  const innerTransform = `translate(${innerDx + view.panX}, ${innerDy + view.panY}) scale(${view.zoom})`;
  const handleSvgPointerDown = (e) => {
    if (e.target !== svgRef.current) return;
    e.currentTarget.setPointerCapture(e.pointerId);
    panStateRef.current = {
      active: true,
      startClientX: e.clientX,
      startClientY: e.clientY,
      startPanX: view.panX,
      startPanY: view.panY
    };
  };
  const handleSvgPointerMove = (e) => {
    const ps = panStateRef.current;
    if (!ps.active) return;
    const svgEl = svgRef.current;
    let scale = 1;
    if (svgEl) {
      const ctm = svgEl.getScreenCTM();
      if (ctm) scale = ctm.a;
    }
    const newPanX = ps.startPanX + (e.clientX - ps.startClientX) / scale;
    const newPanY = ps.startPanY + (e.clientY - ps.startClientY) / scale;
    setView((v) => ({ ...v, panX: newPanX, panY: newPanY }));
  };
  const handleSvgPointerUp = (e) => {
    if (e.currentTarget.hasPointerCapture(e.pointerId)) {
      e.currentTarget.releasePointerCapture(e.pointerId);
    }
    panStateRef.current.active = false;
  };
  const handleWheel = (e) => {
    e.preventDefault();
    const delta = -e.deltaY * 1e-3;
    setView((v) => {
      const newZoom = Math.max(0.25, Math.min(3, v.zoom * (1 + delta)));
      return { ...v, zoom: newZoom };
    });
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "div",
    {
      style: {
        position: "relative",
        background: "var(--card-bg, #ffffff)",
        border: "1px solid var(--border, #d0d7de)",
        overflow: "hidden"
      },
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
          "svg",
          {
            ref: svgRef,
            viewBox: `0 0 ${width} ${height}`,
            width,
            height,
            style: { display: "block", maxWidth: "100%", touchAction: "none" },
            onPointerDown: handleSvgPointerDown,
            onPointerMove: handleSvgPointerMove,
            onPointerUp: handleSvgPointerUp,
            onPointerCancel: handleSvgPointerUp,
            onWheel: handleWheel,
            children: [
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("defs", { children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
                "marker",
                {
                  id: ARROW_ID,
                  viewBox: "0 0 10 10",
                  refX: 10,
                  refY: 5,
                  markerWidth: 6,
                  markerHeight: 6,
                  orient: "auto-start-reverse",
                  children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)("path", { d: "M 0 0 L 10 5 L 0 10 z", fill: EDGE_STROKE })
                }
              ) }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("g", { transform: innerTransform, children: [
                edgeElements,
                nodeElements
              ] })
            ]
          }
        ),
        draggable && /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          "div",
          {
            style: {
              position: "absolute",
              bottom: 6,
              right: 8,
              fontSize: 11,
              color: "var(--text-muted, #656d76)",
              fontFamily: "var(--font-mono, ui-monospace, monospace)",
              letterSpacing: "0.04em",
              pointerEvents: "none"
            },
            children: "drag nodes \u2022 drag empty \u2022 scroll to zoom"
          }
        )
      ]
    }
  );
}

// src/figura/primitives/index.tsx
var import_react4 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(import_jsx_runtime2.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(import_jsx_runtime2.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(import_jsx_runtime2.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react2.default.Children.forEach(children, (child) => {
    if (import_react2.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react3 = __toESM(require_react(), 1);
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react4.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react4.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react4.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react4.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react4.default.createElement("span", null, label), /* @__PURE__ */ import_react4.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react4.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react4.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react4.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react4.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react4.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react4.default.createElement("span", null, label), /* @__PURE__ */ import_react4.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function LegendDot({ color, label }) {
  return /* @__PURE__ */ import_react4.default.createElement("span", { className: "viz-legend-dot" }, /* @__PURE__ */ import_react4.default.createElement("span", { className: "viz-dot", style: { background: color } }), label);
}

// readrun-docs/.readrun/widgets/git-graph-explorer.tsx
var import_jsx_runtime4 = __toESM(require_jsx_runtime(), 1);
var BRANCHES = [
  { id: "main", label: "main", color: "var(--text)" },
  { id: "feature", label: "feature/login", color: "var(--viz-trace)" },
  { id: "release", label: "release/1.2", color: "var(--viz-positive)" },
  { id: "hotfix", label: "hotfix/payments", color: "var(--viz-warn)" }
];
var MODES = [
  { id: "history", label: "History" },
  { id: "ancestry", label: "Ancestry" },
  { id: "refs", label: "Refs" }
];
var COMMITS = [
  {
    id: "a1e4c9",
    title: "initial app shell",
    branch: "main",
    parents: [],
    x: 0,
    y: 360,
    refs: ["tag: v1.0"]
  },
  {
    id: "b62011",
    title: "data loader",
    branch: "main",
    parents: ["a1e4c9"],
    x: 0,
    y: 320
  },
  {
    id: "c83b7a",
    title: "dashboard frame",
    branch: "main",
    parents: ["b62011"],
    x: 0,
    y: 280
  },
  {
    id: "d337ad",
    title: "login branch",
    branch: "feature",
    parents: ["c83b7a"],
    x: -150,
    y: 240
  },
  {
    id: "e7c125",
    title: "oauth callback",
    branch: "feature",
    parents: ["d337ad"],
    x: -150,
    y: 200,
    refs: ["feature/login"]
  },
  {
    id: "f40d72",
    title: "release branch",
    branch: "release",
    parents: ["c83b7a"],
    x: 150,
    y: 240
  },
  {
    id: "g91ab0",
    title: "payment patch",
    branch: "hotfix",
    parents: ["f40d72"],
    x: 275,
    y: 200,
    refs: ["hotfix/payments"]
  },
  {
    id: "h23df8",
    title: "merge hotfix",
    branch: "release",
    parents: ["f40d72", "g91ab0"],
    x: 150,
    y: 160,
    refs: ["release/1.2"]
  },
  {
    id: "i45a0b",
    title: "copy updates",
    branch: "main",
    parents: ["c83b7a"],
    x: 0,
    y: 220
  },
  {
    id: "j8c9e1",
    title: "merge login",
    branch: "main",
    parents: ["i45a0b", "e7c125"],
    x: 0,
    y: 120
  },
  {
    id: "k135aa",
    title: "ship release",
    branch: "main",
    parents: ["j8c9e1", "h23df8"],
    x: 0,
    y: 80,
    refs: ["main", "HEAD"]
  }
];
var STEPS = [
  {
    label: "init",
    command: 'git init\ngit add .\ngit commit -m "initial app shell"\ngit tag v1.0',
    description: "Repository starts on main with a single root commit.",
    branch: "main",
    visibleCount: 1,
    focusCommit: "a1e4c9",
    changes: ["Created package.json", "Created src/app.tsx", "Tagged baseline as v1.0"],
    result: "main and tag v1.0 point at a1e4c9."
  },
  {
    label: "commit",
    command: 'git commit -m "data loader"',
    description: "main advances by one ordinary commit.",
    branch: "main",
    visibleCount: 2,
    focusCommit: "b62011",
    changes: ["Added src/data/loaders.ts", "Updated README usage notes"],
    result: "HEAD moves from a1e4c9 to b62011."
  },
  {
    label: "commit",
    command: 'git commit -m "dashboard frame"',
    description: "A shared UI frame lands before branch work begins.",
    branch: "main",
    visibleCount: 3,
    focusCommit: "c83b7a",
    changes: ["Added src/dashboard/frame.tsx", "Adjusted layout styles"],
    result: "c83b7a becomes the common ancestor for later branches."
  },
  {
    label: "branch",
    command: 'git switch -c feature/login\ngit add src/auth/login-form.tsx\ngit commit -m "login branch"',
    description: "A feature branch forks from main, then records its first feature commit.",
    branch: "feature",
    visibleCount: 4,
    focusCommit: "d337ad",
    changes: ["Added login form scaffold", "No main files changed after branch point"],
    result: "feature/login points at d337ad while main remains at c83b7a."
  },
  {
    label: "commit",
    command: 'git commit -m "oauth callback"',
    description: "More work is committed on feature/login.",
    branch: "feature",
    visibleCount: 5,
    focusCommit: "e7c125",
    changes: ["Added src/auth/oauth.ts", "Updated tests for callback parsing"],
    result: "feature/login advances to e7c125."
  },
  {
    label: "branch",
    command: 'git switch -c release/1.2 c83b7a\ngit add docs/release-notes.md src/dashboard/copy.ts\ngit commit -m "release branch"',
    description: "A release branch starts from the stable dashboard frame, then commits release prep.",
    branch: "release",
    visibleCount: 6,
    focusCommit: "f40d72",
    changes: ["Prepared release notes", "Pinned dashboard copy for release"],
    result: "release/1.2 diverges from main and feature/login."
  },
  {
    label: "hotfix",
    command: 'git switch -c hotfix/payments\ngit add src/payments/checkout.ts src/payments/checkout.test.ts\ngit commit -m "payment patch"',
    description: "A short hotfix branch fixes release-critical payment behavior.",
    branch: "hotfix",
    visibleCount: 7,
    focusCommit: "g91ab0",
    changes: ["Patched src/payments/checkout.ts", "Added regression test"],
    result: "hotfix/payments points at g91ab0."
  },
  {
    label: "merge",
    command: "git switch release/1.2 && git merge hotfix/payments",
    description: "The hotfix is merged into the release branch.",
    branch: "release",
    visibleCount: 8,
    focusCommit: "h23df8",
    changes: ["Merged checkout fix into release/1.2", "No feature/login files included"],
    result: "h23df8 has two parents: f40d72 and g91ab0."
  },
  {
    label: "commit",
    command: 'git switch main && git commit -m "copy updates"',
    description: "main continues independently while branches are open.",
    branch: "main",
    visibleCount: 9,
    focusCommit: "i45a0b",
    changes: ["Edited src/dashboard/copy.ts", "Updated docs/changelog.md"],
    result: "main advances to i45a0b without pulling in feature/login yet."
  },
  {
    label: "merge",
    command: "git merge feature/login",
    description: "The login feature branch is merged back into main.",
    branch: "main",
    visibleCount: 10,
    focusCommit: "j8c9e1",
    changes: ["Integrated src/auth/oauth.ts", "Resolved dashboard route conflict"],
    result: "j8c9e1 joins main history with feature/login history."
  },
  {
    label: "merge",
    command: "git merge release/1.2",
    description: "Release branch changes and hotfix history are brought into main.",
    branch: "main",
    visibleCount: 11,
    focusCommit: "k135aa",
    changes: ["Brought payment hotfix into main", "Moved main and HEAD to final merge"],
    result: "HEAD and main now point at k135aa."
  }
];
function branchColor(branch) {
  return BRANCHES.find((b) => b.id === branch)?.color ?? "var(--text-muted)";
}
function isBranch(value) {
  return value === "main" || value === "feature" || value === "release" || value === "hotfix";
}
function refsOf(node) {
  return Array.isArray(node.refs) ? node.refs.filter((ref) => typeof ref === "string") : [];
}
function buildEdges(commits) {
  const ids = new Set(commits.map((commit) => commit.id));
  return commits.flatMap(
    (commit) => commit.parents.filter((parent) => ids.has(parent)).map((parent) => ({
      id: `${commit.id}-${parent}`,
      from: commit.id,
      to: parent,
      branch: commit.branch
    }))
  );
}
function ancestryIds(selectedId, commits) {
  const byId = new Map(commits.map((commit) => [commit.id, commit]));
  const out = /* @__PURE__ */ new Set([selectedId]);
  const stack = [selectedId];
  while (stack.length > 0) {
    const current = byId.get(stack.pop() ?? "");
    if (!current) continue;
    for (const parent of current.parents) {
      if (out.has(parent)) continue;
      out.add(parent);
      stack.push(parent);
    }
  }
  return out;
}
function toNodes(commits) {
  return commits.map((commit) => ({
    ...commit,
    label: commit.id,
    width: commit.parents.length > 1 ? 88 : 78,
    height: commit.parents.length > 1 ? 32 : 28
  }));
}
function edgeBranch(edge2) {
  return isBranch(edge2.branch) ? edge2.branch : "main";
}
function mergeCount(commits) {
  return commits.filter((commit) => commit.parents.length > 1).length;
}
function GitNode({
  node,
  selected,
  dimmed,
  onSelect
}) {
  const branch = isBranch(node.branch) ? node.branch : "main";
  const refs = refsOf(node);
  const color = branchColor(branch);
  const isMerge = Array.isArray(node.parents) && node.parents.length > 1;
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)(
    "g",
    {
      transform: `translate(${node.x - node.width / 2}, ${node.y - node.height / 2})`,
      onClick: () => onSelect(node.id),
      style: { cursor: "pointer", opacity: dimmed ? 0.25 : 1 },
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          "rect",
          {
            width: node.width,
            height: node.height,
            fill: "var(--bg)",
            stroke: selected ? "var(--text)" : color,
            strokeWidth: selected ? 2.5 : 1.5,
            rx: 0
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("rect", { width: 6, height: node.height, fill: color }),
        isMerge && /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          "path",
          {
            d: `M ${node.width - 13} 7 L ${node.width - 6} ${node.height / 2} L ${node.width - 13} ${node.height - 7} L ${node.width - 20} ${node.height / 2} Z`,
            fill: "none",
            stroke: color,
            strokeWidth: 1.2
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          "text",
          {
            x: 14,
            y: node.height / 2 + 4,
            fontSize: 11,
            fill: "var(--text)",
            fontFamily: "var(--font-mono, ui-monospace, monospace)",
            style: { userSelect: "none" },
            children: node.id
          }
        ),
        refs.map((ref, index) => {
          const refWidth = Math.max(42, ref.length * 7 + 10);
          const refX = node.x > 170 ? -refWidth - 8 : node.width + 8;
          return /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("g", { transform: `translate(${refX}, ${index * 18 - 2})`, children: [
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
              "rect",
              {
                width: refWidth,
                height: 15,
                fill: "var(--input-bg)",
                stroke: "var(--border)"
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
              "text",
              {
                x: 5,
                y: 11,
                fontSize: 11,
                fill: "var(--text-muted)",
                fontFamily: "var(--font-mono, ui-monospace, monospace)",
                style: { userSelect: "none" },
                children: ref
              }
            )
          ] }, ref);
        })
      ]
    }
  );
}
function DetailRow({ label, value }) {
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "flex", justifyContent: "space-between", gap: 12 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("span", { style: { color: "var(--text-muted)" }, children: label }),
    /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("strong", { style: { fontFamily: "var(--font-mono, ui-monospace, monospace)", textAlign: "right" }, children: value })
  ] });
}
function StepBadge({ step }) {
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
    "span",
    {
      style: {
        display: "inline-flex",
        alignItems: "center",
        border: "1px solid var(--border)",
        background: "var(--input-bg)",
        padding: "3px 7px",
        fontSize: 11,
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
        color: "var(--text-muted)"
      },
      children: step.label
    }
  );
}
function GitGraphExplorer() {
  const [stepIndex, setStepIndex] = (0, import_react5.useState)(STEPS.length - 1);
  const [mode, setMode] = (0, import_react5.useState)("history");
  const [selectedId, setSelectedId] = (0, import_react5.useState)(STEPS[STEPS.length - 1]?.focusCommit ?? "");
  const step = STEPS[stepIndex] ?? STEPS[STEPS.length - 1];
  const visibleCommits = (0, import_react5.useMemo)(() => COMMITS.slice(0, step.visibleCount), [step.visibleCount]);
  const visibleIds = (0, import_react5.useMemo)(
    () => new Set(visibleCommits.map((commit) => commit.id)),
    [visibleCommits]
  );
  const refIds = (0, import_react5.useMemo)(
    () => new Set(visibleCommits.filter((commit) => commit.refs?.length).map((commit) => commit.id)),
    [visibleCommits]
  );
  const activeId = visibleIds.has(selectedId) ? selectedId : step.focusCommit;
  const selectedCommit = visibleIds.has(activeId) ? visibleCommits.find((commit) => commit.id === activeId) : visibleCommits[visibleCommits.length - 1];
  const focusedId = selectedCommit?.id ?? step.focusCommit;
  const ancestry = (0, import_react5.useMemo)(
    () => ancestryIds(focusedId, visibleCommits),
    [focusedId, visibleCommits]
  );
  const edges = (0, import_react5.useMemo)(() => buildEdges(visibleCommits), [visibleCommits]);
  const stepCommit = visibleIds.has(step.focusCommit) ? visibleCommits.find((commit) => commit.id === step.focusCommit) : void 0;
  const dimForMode = (id) => mode === "ancestry" && !ancestry.has(id) || mode === "refs" && !refIds.has(id) && id !== focusedId;
  const visibleRefs = visibleCommits.flatMap((commit) => commit.refs ?? []);
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)(
    WidgetLayout,
    {
      arrangement: "visual-left",
      title: "Git Graph Explorer",
      subtitle: "Scrub through Git commands and watch branch refs, merge commits, and file changes accumulate.",
      headMeta: /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)(import_jsx_runtime4.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Stat, { label: "commits", value: visibleCommits.length }),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Stat, { label: "merges", value: mergeCount(visibleCommits) })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(WidgetLayout.Visual, { children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("div", { style: { padding: 12 }, children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          Flow,
          {
            nodes: toNodes(visibleCommits),
            edges,
            layout: "manual",
            edgeRouter: "curve",
            width: 720,
            height: 430,
            draggable: false,
            renderEdge: (_, edge2, fromNode, toNode) => {
              const selectedEdge = focusedId === edge2.from || focusedId === edge2.to;
              const ancestryEdge = mode === "ancestry" && ancestry.has(edge2.from) && ancestry.has(edge2.to);
              const refEdge = mode === "refs" && (refIds.has(edge2.from) || refIds.has(edge2.to));
              const highlighted = selectedEdge || ancestryEdge || refEdge;
              const dimmed = mode === "ancestry" && !highlighted || mode === "refs" && !highlighted;
              const color = branchColor(edgeBranch(edge2));
              const midY = (fromNode.y + toNode.y) / 2;
              const path = `M ${fromNode.x} ${fromNode.y} C ${fromNode.x} ${midY}, ${toNode.x} ${midY}, ${toNode.x} ${toNode.y}`;
              return /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
                "path",
                {
                  d: path,
                  fill: "none",
                  stroke: color,
                  strokeWidth: highlighted ? 2.5 : 1.4,
                  opacity: dimmed ? 0.18 : 0.75
                },
                edge2.id
              );
            },
            renderNode: (node) => /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
              GitNode,
              {
                node,
                selected: node.id === focusedId,
                dimmed: dimForMode(node.id),
                onSelect: setSelectedId
              }
            )
          }
        ) }) }),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)(WidgetLayout.Controls, { children: [
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
            Slider,
            {
              label: "command step",
              min: 1,
              max: STEPS.length,
              step: 1,
              value: stepIndex + 1,
              onChange: (value) => {
                const nextIndex = value - 1;
                setStepIndex(nextIndex);
                const next = STEPS[nextIndex];
                if (next) setSelectedId(next.focusCommit);
              },
              format: (value) => `${value.toFixed(0)} / ${STEPS.length}`
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "flex", gap: 8, alignItems: "center", marginBottom: 12 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(StepBadge, { step }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("strong", { children: step.description })
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(SectionLabel, { children: "Commands run" }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
            "pre",
            {
              style: {
                margin: "0 0 12px",
                padding: 10,
                overflowX: "auto",
                background: "var(--input-bg)",
                border: "1px solid var(--border)",
                color: "var(--text)",
                fontSize: 11,
                lineHeight: 1.45
              },
              children: step.command
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(SectionLabel, { children: "What changed" }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("ul", { style: { margin: "0 0 12px", paddingLeft: 18, lineHeight: 1.55, fontSize: 11 }, children: step.changes.map((change) => /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("li", { children: change }, change)) }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "grid", gap: 7, fontSize: 11, marginBottom: 14 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(DetailRow, { label: "active branch", value: step.branch }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(DetailRow, { label: "focused commit", value: step.focusCommit }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(DetailRow, { label: "result", value: step.result }),
            stepCommit && /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
              DetailRow,
              {
                label: "parents",
                value: stepCommit.parents.length ? stepCommit.parents.join(" ") : "root"
              }
            )
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Tabs, { value: mode, onChange: (id) => setMode(id), items: MODES }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(SectionLabel, { style: { marginTop: 14 }, children: "Branches" }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("div", { style: { display: "flex", flexDirection: "column", gap: 7, marginBottom: 14 }, children: BRANCHES.map((branch) => /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(LegendDot, { color: branch.color, label: branch.label }, branch.id)) }),
          selectedCommit && selectedCommit.id !== step.focusCommit && /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "grid", gap: 7, fontSize: 11 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(SectionLabel, { children: "Clicked commit" }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(DetailRow, { label: "sha", value: selectedCommit.id }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(DetailRow, { label: "message", value: selectedCommit.title })
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 14 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Btn, { kind: "ghost", onClick: () => setSelectedId(COMMITS[0]?.id ?? ""), children: "Root" }),
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
              Btn,
              {
                kind: "ghost",
                onClick: () => setSelectedId(step.focusCommit),
                children: "Step focus"
              }
            )
          ] })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(WidgetLayout.Aside, { children: /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("ul", { style: { margin: 0, paddingLeft: 18, lineHeight: 1.55 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("li", { children: "The slider is the story spine: each stop is one command and the graph only shows the commits that exist after that command." }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("li", { children: "The right panel names changed files, moved branches, parent links, and merge effects." }),
          /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("li", { children: visibleRefs.length > 0 ? /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)(import_jsx_runtime4.Fragment, { children: [
            "Current visible refs: ",
            /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("code", { children: visibleRefs.join(", ") }),
            "."
          ] }) : "Move the scrubber forward to reveal branch and tag refs." })
        ] }) })
      ]
    }
  );
}
render(<GitGraphExplorer />);
