// generated by @readrun/widgets — edit .readrun/widgets/gradient-descent.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/gradient-descent.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/gradient-descent.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var OPTS = [
  { id: "sgd", label: "SGD" },
  { id: "momentum", label: "Momentum" },
  { id: "adam", label: "Adam" }
];
function loss(x, y) {
  return 1.2 * (x - 1) * (x - 1) + 0.6 * (y + 0.5) * (y + 0.5) + 0.6 * Math.sin(2 * x) * Math.cos(2 * y);
}
function grad(x, y) {
  return [
    2 * 1.2 * (x - 1) + 1.2 * Math.cos(2 * x) * Math.cos(2 * y),
    2 * 0.6 * (y + 0.5) - 1.2 * Math.sin(2 * x) * Math.sin(2 * y)
  ];
}
function GradientDescent() {
  const W = 520;
  const H = 420;
  const xMin = -2;
  const xMax = 4;
  const yMin = -2;
  const yMax = 2;
  const toS = (x2, y2) => [
    (x2 - xMin) / (xMax - xMin) * W,
    H - (y2 - yMin) / (yMax - yMin) * H
  ];
  const toW = (sx, sy) => [
    xMin + sx / W * (xMax - xMin),
    yMin + (H - sy) / H * (yMax - yMin)
  ];
  const [start, setStart] = (0, import_react4.useState)([-1, 1.5]);
  const [opt, setOpt] = (0, import_react4.useState)("sgd");
  const [lr, setLr] = (0, import_react4.useState)(0.06);
  const [steps, setSteps] = (0, import_react4.useState)(60);
  const svgRef = (0, import_react4.useRef)(null);
  const path = [];
  let x = start[0];
  let y = start[1];
  let mx = 0;
  let my = 0;
  let vx2 = 0;
  let vy2 = 0;
  const beta1 = 0.9;
  const beta2 = 0.999;
  const eps = 1e-8;
  path.push([x, y]);
  for (let i = 1; i <= steps; i++) {
    const [gx, gy] = grad(x, y);
    if (opt === "sgd") {
      x -= lr * gx;
      y -= lr * gy;
    } else if (opt === "momentum") {
      mx = 0.9 * mx + gx;
      my = 0.9 * my + gy;
      x -= lr * mx;
      y -= lr * my;
    } else {
      mx = beta1 * mx + (1 - beta1) * gx;
      my = beta1 * my + (1 - beta1) * gy;
      vx2 = beta2 * vx2 + (1 - beta2) * gx * gx;
      vy2 = beta2 * vy2 + (1 - beta2) * gy * gy;
      const mhx = mx / (1 - Math.pow(beta1, i));
      const mhy = my / (1 - Math.pow(beta1, i));
      const vhx = vx2 / (1 - Math.pow(beta2, i));
      const vhy = vy2 / (1 - Math.pow(beta2, i));
      x -= lr * 4 * (mhx / (Math.sqrt(vhx) + eps));
      y -= lr * 4 * (mhy / (Math.sqrt(vhy) + eps));
    }
    path.push([x, y]);
  }
  const finalLoss = loss(path.at(-1)[0], path.at(-1)[1]);
  const cells = 60;
  const cw = W / cells;
  const ch = H / cells;
  const heat = [];
  let lMin = Infinity;
  let lMax = -Infinity;
  for (let i = 0; i < cells; i++) {
    for (let j = 0; j < cells; j++) {
      const wx = xMin + (i + 0.5) / cells * (xMax - xMin);
      const wy = yMin + (j + 0.5) / cells * (yMax - yMin);
      const v = loss(wx, wy);
      if (v < lMin) lMin = v;
      if (v > lMax) lMax = v;
      heat.push({ x: i * cw, y: H - (j + 1) * ch, v });
    }
  }
  const [drag, setDrag] = (0, import_react4.useState)(false);
  const onMove = (e) => {
    if (!drag || !svgRef.current) return;
    const rect = svgRef.current.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (W / rect.width);
    const sy = (e.clientY - rect.top) * (H / rect.height);
    setStart(toW(sx, sy));
  };
  const meta = /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "step", value: steps }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "loss", value: finalLoss.toFixed(4), color: "var(--viz-trace)" })
  ] });
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Shell, { title: "Gradient Descent", meta, children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Drag the marble to choose a starting point. Three optimizers race over the same loss surface \u2014 vanilla SGD, momentum (\u03B2 = 0.9), and Adam." }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
        "svg",
        {
          ref: svgRef,
          viewBox: `0 0 ${W} ${H}`,
          width: W,
          height: H,
          style: { display: "block", touchAction: "none", maxWidth: "100%" },
          onPointerDown: (e) => {
            setDrag(true);
            const rect = svgRef.current.getBoundingClientRect();
            setStart(toW((e.clientX - rect.left) * (W / rect.width), (e.clientY - rect.top) * (H / rect.height)));
          },
          onPointerMove: onMove,
          onPointerUp: () => setDrag(false),
          onPointerLeave: () => setDrag(false),
          children: [
            heat.map((c, i) => {
              const t = (c.v - lMin) / (lMax - lMin + 1e-9);
              const a = 0.18 + t * 0.55;
              return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                "rect",
                {
                  x: c.x,
                  y: c.y,
                  width: cw + 0.5,
                  height: ch + 0.5,
                  fill: "var(--viz-trace)",
                  fillOpacity: a
                },
                i
              );
            }),
            [5, 10, 20, 40].map((iso) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("g", {}, iso)),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polyline",
              {
                points: path.map(([px, py]) => toS(px, py).join(",")).join(" "),
                fill: "none",
                stroke: "var(--viz-warn)",
                strokeWidth: "2.5",
                opacity: "0.95"
              }
            ),
            path.map(
              (p, i) => i % 4 === 0 ? /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: toS(p[0], p[1])[0], cy: toS(p[0], p[1])[1], r: 2.5, fill: "var(--viz-warn)" }, i) : null
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "circle",
              {
                cx: toS(start[0], start[1])[0],
                cy: toS(start[0], start[1])[1],
                r: 9,
                fill: "var(--viz-warn)",
                stroke: "var(--bg)",
                strokeWidth: "2.5",
                style: { cursor: "grab" }
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "circle",
              {
                cx: toS(path.at(-1)[0], path.at(-1)[1])[0],
                cy: toS(path.at(-1)[0], path.at(-1)[1])[1],
                r: 6,
                fill: "var(--viz-positive)",
                stroke: "var(--bg)",
                strokeWidth: "2"
              }
            )
          ]
        }
      ) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 240, children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Optimizer" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Tabs, { value: opt, onChange: (id) => setOpt(id), items: OPTS }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "learning rate", min: 5e-3, max: 0.25, step: 5e-3, value: lr, onChange: setLr }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
          Slider,
          {
            label: "steps",
            min: 5,
            max: 250,
            step: 5,
            value: steps,
            onChange: setSteps,
            format: (v) => `${v}`
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 6 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setStart([-1, 1.5]), children: "top-left" }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setStart([3, 1.5]), children: "top-right" }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setStart([3, -1.5]), children: "bottom-right" }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setStart([-1, -1.5]), children: "bottom-left" })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
          " SGD with high learning rate oscillates across the valley. Momentum smooths it out by accumulating gradient history. Adam adapts the step size per dimension \u2014 robust to starting point and lr."
        ] })
      ] })
    ] })
  ] });
}
render(<GradientDescent />);
