// generated by @readrun/widgets — edit .readrun/widgets/is-lm-explorer.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/is-lm-explorer.tsx
var import_react8 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// src/figura/plot/Frame.tsx
var import_react5 = __toESM(require_react(), 1);

// src/figura/plot/Axis.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/plot/ticks.ts
function ticks(s, n) {
  if (s.type === "ordinal") {
    return [...s.domain];
  }
  const cs = s;
  if (cs.type === "log") {
    return logTicks(cs);
  }
  return linearTicks(cs, n);
}
function linearTicks(s, n) {
  const [d0, d1] = s.domain;
  const span = d1 - d0;
  const count = Math.max(n, 2);
  const roughStep = span / count;
  const mag = Math.floor(Math.log10(roughStep));
  const base = Math.pow(10, mag);
  let step;
  const r = roughStep / base;
  if (r <= 1) {
    step = base;
  } else if (r <= 2) {
    step = 2 * base;
  } else if (r <= 5) {
    step = 5 * base;
  } else {
    step = 10 * base;
  }
  const start = Math.ceil(d0 / step) * step;
  const end = Math.floor(d1 / step) * step;
  const result = [];
  const numSteps = Math.round((end - start) / step);
  for (let i = 0; i <= numSteps; i++) {
    const v = start + i * step;
    const rounded = parseFloat(v.toPrecision(12));
    result.push(rounded);
  }
  if (result.length < 2) {
    return [d0, d1];
  }
  return result;
}
function logTicks(s) {
  const [d0, d1] = s.domain;
  const result = [];
  const logD0 = Math.log10(d0);
  const logD1 = Math.log10(d1);
  const startExp = Math.floor(logD0);
  const endExp = Math.ceil(logD1);
  for (let exp = startExp; exp <= endExp; exp++) {
    const v = Math.pow(10, exp);
    if (v >= d0 && v <= d1) {
      result.push(v);
    }
  }
  if (result.length < 2) {
    return [d0, d1];
  }
  return result;
}

// src/figura/plot/Axis.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var TICK_SIZE = 6;
var AXIS_COLOR = "#64748b";
var LABEL_COLOR = "#475569";
var FONT = "ui-monospace, monospace";
var FONT_SIZE = 11;
function Axis({
  scale: scale2,
  side,
  label,
  tickFormat = String,
  numTicks = 5
}) {
  const isHorizontal = side === "bottom" || side === "top";
  const tickValues = ticks(scale2, numTicks);
  function tickPos(value) {
    if (scale2.type === "ordinal") {
      return scale2(value);
    }
    return scale2(value);
  }
  const [r0, r1] = scale2.range;
  const lineLength = r1 - r0;
  const tickDir = side === "bottom" || side === "right" ? 1 : -1;
  if (isHorizontal) {
    const labelOffset = side === "bottom" ? TICK_SIZE + 14 : -(TICK_SIZE + 14);
    const axisLabelY = side === "bottom" ? TICK_SIZE + 28 : -(TICK_SIZE + 28);
    return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "line",
        {
          x1: r0,
          y1: 0,
          x2: r1,
          y2: 0,
          stroke: AXIS_COLOR,
          strokeWidth: 1
        }
      ),
      tickValues.map((v) => {
        const x = tickPos(v);
        return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { transform: `translate(${x}, 0)`, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "line",
            {
              x1: 0,
              y1: 0,
              x2: 0,
              y2: tickDir * TICK_SIZE,
              stroke: AXIS_COLOR,
              strokeWidth: 1
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "text",
            {
              x: 0,
              y: labelOffset,
              textAnchor: "middle",
              dominantBaseline: side === "bottom" ? "hanging" : "auto",
              style: {
                fontFamily: FONT,
                fontSize: FONT_SIZE,
                fill: LABEL_COLOR
              },
              children: tickFormat(v)
            }
          )
        ] }, String(v));
      }),
      label && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "text",
        {
          x: (r0 + r1) / 2,
          y: axisLabelY,
          textAnchor: "middle",
          dominantBaseline: side === "bottom" ? "hanging" : "auto",
          style: {
            fontFamily: FONT,
            fontSize: FONT_SIZE,
            fill: LABEL_COLOR,
            fontWeight: 500
          },
          children: label
        }
      )
    ] });
  } else {
    const labelOffset = side === "left" ? -(TICK_SIZE + 6) : TICK_SIZE + 6;
    const textAnchor = side === "left" ? "end" : "start";
    const axisLabelOffset = side === "left" ? -(TICK_SIZE + 36) : TICK_SIZE + 36;
    return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "line",
        {
          x1: 0,
          y1: r0,
          x2: 0,
          y2: lineLength < 0 ? r0 + lineLength : r1,
          stroke: AXIS_COLOR,
          strokeWidth: 1
        }
      ),
      tickValues.map((v) => {
        const y = tickPos(v);
        return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { transform: `translate(0, ${y})`, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "line",
            {
              x1: 0,
              y1: 0,
              x2: tickDir * -TICK_SIZE,
              y2: 0,
              stroke: AXIS_COLOR,
              strokeWidth: 1
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "text",
            {
              x: labelOffset,
              y: 0,
              textAnchor,
              dominantBaseline: "middle",
              style: {
                fontFamily: FONT,
                fontSize: FONT_SIZE,
                fill: LABEL_COLOR
              },
              children: tickFormat(v)
            }
          )
        ] }, String(v));
      }),
      label && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "text",
        {
          x: axisLabelOffset,
          y: (r0 + (lineLength < 0 ? r0 + lineLength : r1)) / 2,
          textAnchor: "middle",
          transform: `rotate(-90, ${axisLabelOffset}, ${(r0 + (lineLength < 0 ? r0 + lineLength : r1)) / 2})`,
          style: {
            fontFamily: FONT,
            fontSize: FONT_SIZE,
            fill: LABEL_COLOR,
            fontWeight: 500
          },
          children: label
        }
      )
    ] });
  }
}

// src/figura/plot/Frame.tsx
var import_jsx_runtime4 = __toESM(require_jsx_runtime(), 1);
var DEFAULT_MARGIN = { top: 10, right: 10, bottom: 30, left: 40 };
function Frame({
  width,
  height,
  margin: marginProp,
  xScale,
  yScale,
  xLabel,
  yLabel,
  xTickFormat,
  yTickFormat,
  xNumTicks,
  yNumTicks,
  children
}) {
  const margin = {
    top: marginProp?.top ?? DEFAULT_MARGIN.top,
    right: marginProp?.right ?? DEFAULT_MARGIN.right,
    bottom: marginProp?.bottom ?? DEFAULT_MARGIN.bottom,
    left: marginProp?.left ?? DEFAULT_MARGIN.left
  };
  const innerWidth = width - margin.left - margin.right;
  const innerHeight = height - margin.top - margin.bottom;
  const renderArgs = {
    xScale,
    yScale,
    innerWidth,
    innerHeight
  };
  const content = typeof children === "function" ? children(renderArgs) : children;
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
    "svg",
    {
      viewBox: `0 0 ${width} ${height}`,
      width,
      height,
      style: { display: "block", maxWidth: "100%" },
      children: /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("g", { transform: `translate(${margin.left}, ${margin.top})`, children: [
        content,
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("g", { transform: `translate(0, ${innerHeight})`, children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          Axis,
          {
            scale: xScale,
            side: "bottom",
            label: xLabel,
            tickFormat: xTickFormat,
            numTicks: xNumTicks
          }
        ) }),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("g", { transform: "translate(0, 0)", children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          Axis,
          {
            scale: yScale,
            side: "left",
            label: yLabel,
            tickFormat: yTickFormat,
            numTicks: yNumTicks
          }
        ) })
      ] })
    }
  );
}

// src/figura/plot/scale.ts
function makeLinear(domain, range) {
  const [d0, d1] = domain;
  const [r0, r1] = range;
  const fn = (value) => {
    return (value - d0) / (d1 - d0) * (r1 - r0) + r0;
  };
  const s = fn;
  s.invert = (n) => (n - r0) / (r1 - r0) * (d1 - d0) + d0;
  s.domain = domain;
  s.range = range;
  s.type = "linear";
  return s;
}
function makeLog(domain, range, base) {
  const [d0, d1] = domain;
  if (d0 <= 0 || d1 <= 0) {
    throw new Error(
      `scale.log: domain values must be > 0, got [${d0}, ${d1}]`
    );
  }
  const logBase = Math.log(base);
  const logD0 = Math.log(d0) / logBase;
  const logD1 = Math.log(d1) / logBase;
  const [r0, r1] = range;
  const fn = (value) => {
    const logV = Math.log(value) / logBase;
    return (logV - logD0) / (logD1 - logD0) * (r1 - r0) + r0;
  };
  const s = fn;
  s.invert = (n) => {
    const logV = (n - r0) / (r1 - r0) * (logD1 - logD0) + logD0;
    return Math.pow(base, logV);
  };
  s.domain = domain;
  s.range = range;
  s.type = "log";
  return s;
}
function makeOrdinal(domain, range) {
  const [r0, r1] = range;
  const bw = (r1 - r0) / domain.length;
  const fn = (value) => {
    const idx = domain.indexOf(value);
    if (idx === -1) {
      throw new Error(
        `scale.ordinal: value ${String(value)} not in domain [${domain.join(", ")}]`
      );
    }
    return r0 + idx * bw + bw / 2;
  };
  const s = fn;
  s.domain = domain;
  s.range = range;
  s.bandwidth = bw;
  s.type = "ordinal";
  return s;
}
var scale = {
  linear({
    domain,
    range
  }) {
    return makeLinear(domain, range);
  },
  log({
    domain,
    range,
    base = 10
  }) {
    return makeLog(domain, range, base);
  },
  ordinal({
    domain,
    range
  }) {
    return makeOrdinal(domain, range);
  }
};

// src/figura/plot/Heatmap.tsx
var import_react6 = __toESM(require_react(), 1);
var import_jsx_runtime5 = __toESM(require_jsx_runtime(), 1);

// src/figura/plot/Histogram.tsx
var import_react7 = __toESM(require_react(), 1);
var import_jsx_runtime6 = __toESM(require_jsx_runtime(), 1);

// readrun-docs/.readrun/widgets/is-lm-explorer.model.ts
var DEFAULT_PARAMS = {
  c0: 100,
  c1: 0.6,
  i0: 200,
  b: 20,
  G: 100,
  T: 50,
  k: 0.5,
  h: 10,
  M: 200
};
function equilibrium(p) {
  const A = p.c0 + p.i0 + p.G - p.c1 * p.T;
  const denom = p.h * (1 - p.c1) + p.b * p.k;
  if (denom <= 0) return null;
  const Yeq = (A * p.h + p.b * p.M) / denom;
  const rEq = (p.k * Yeq - p.M) / p.h;
  if (!Number.isFinite(Yeq) || !Number.isFinite(rEq)) return null;
  if (Yeq < 0 || rEq < 0) return null;
  return { Yeq, rEq };
}
function isCurvePoints(p, rRange, n = 60) {
  const A = p.c0 + p.i0 + p.G - p.c1 * p.T;
  const out = [];
  for (let i = 0; i <= n; i++) {
    const r = rRange[0] + (rRange[1] - rRange[0]) * (i / n);
    const Y = (A - p.b * r) / (1 - p.c1);
    out.push([Y, r]);
  }
  return out;
}
function lmCurvePoints(p, yRange, n = 60) {
  const out = [];
  for (let i = 0; i <= n; i++) {
    const Y = yRange[0] + (yRange[1] - yRange[0]) * (i / n);
    const r = (p.k * Y - p.M) / p.h;
    out.push([Y, r]);
  }
  return out;
}
function moneyDemandPoints(p, yFixed, rRange, n = 60) {
  const out = [];
  for (let i = 0; i <= n; i++) {
    const r = rRange[0] + (rRange[1] - rRange[0]) * (i / n);
    const M = p.k * yFixed - p.h * r;
    out.push([M, r]);
  }
  return out;
}

// readrun-docs/.readrun/widgets/is-lm-explorer.tsx
var import_jsx_runtime7 = __toESM(require_jsx_runtime(), 1);
var R_DOMAIN = [0, 25];
var M_DOMAIN = [0, 600];
var Y_DOMAIN = [0, 1100];
var FRAME_W = 240;
var FRAME_H = 280;
var INNER_W = 190;
var INNER_H = 240;
var mmXScale = scale.linear({ domain: M_DOMAIN, range: [0, INNER_W] });
var gmXScale = scale.linear({ domain: Y_DOMAIN, range: [0, INNER_W] });
var rScale = scale.linear({ domain: R_DOMAIN, range: [INNER_H, 0] });
function IsLmExplorer() {
  const [params, setParams] = (0, import_react8.useState)(DEFAULT_PARAMS);
  const [showAdvanced, setShowAdvanced] = (0, import_react8.useState)(false);
  const eq = equilibrium(params);
  const setP = (patch) => setParams((p) => ({ ...p, ...patch }));
  const reset = () => setParams(DEFAULT_PARAMS);
  return /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(
    WidgetLayout,
    {
      arrangement: "visual-left",
      title: "IS-LM Explorer",
      subtitle: /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(import_jsx_runtime7.Fragment, { children: [
        "Two side-by-side panels share interest rate ",
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "r" }),
        " on the y-axis. Move the sliders to see how monetary policy (M) and fiscal policy (G, T) propagate through both markets."
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(WidgetLayout.Visual, { children: !eq ? /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(Notice, { children: [
          "No equilibrium in the feasible range. Try moving the sliders back toward the centre or click ",
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("strong", { children: "Reset" }),
          "."
        ] }) : /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { display: "flex", gap: 16, flexWrap: "wrap" }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(MoneyMarketPanel, { params, eq }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(GoodsMarketPanel, { params, eq })
        ] }) }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(WidgetLayout.Controls, { children: [
          eq && /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(
            "div",
            {
              className: "viz-stat-row",
              style: { marginTop: 0, display: "flex", gap: 16, flexWrap: "wrap" },
              children: [
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "r*", value: eq.rEq.toFixed(2) }),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "Y*", value: eq.Yeq.toFixed(0) }),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "M", value: params.M.toFixed(0) }),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "G", value: params.G.toFixed(0) }),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "T", value: params.T.toFixed(0) })
              ]
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(
            "div",
            {
              style: { marginTop: 12, display: "flex", flexDirection: "column", gap: 0 },
              children: [
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "M",
                    value: params.M,
                    min: 50,
                    max: 500,
                    step: 5,
                    onChange: (v) => setP({ M: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "G",
                    value: params.G,
                    min: 0,
                    max: 300,
                    step: 5,
                    onChange: (v) => setP({ G: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "T",
                    value: params.T,
                    min: 0,
                    max: 200,
                    step: 5,
                    onChange: (v) => setP({ T: v })
                  }
                )
              ]
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { marginTop: 8, display: "flex", gap: 8 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Btn, { kind: "ghost", onClick: () => setShowAdvanced((v) => !v), children: showAdvanced ? "hide" : "show all parameters" }),
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Btn, { kind: "ghost", onClick: reset, children: "Reset" })
          ] }),
          showAdvanced && /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(
            "div",
            {
              style: { marginTop: 12, display: "flex", flexDirection: "column", gap: 0 },
              children: [
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "c0",
                    value: params.c0,
                    min: 50,
                    max: 200,
                    step: 5,
                    onChange: (v) => setP({ c0: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "c1",
                    value: params.c1,
                    min: 0.3,
                    max: 0.9,
                    step: 0.05,
                    onChange: (v) => setP({ c1: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "i0",
                    value: params.i0,
                    min: 100,
                    max: 400,
                    step: 5,
                    onChange: (v) => setP({ i0: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "b",
                    value: params.b,
                    min: 5,
                    max: 50,
                    step: 1,
                    onChange: (v) => setP({ b: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "k",
                    value: params.k,
                    min: 0.2,
                    max: 1,
                    step: 0.05,
                    onChange: (v) => setP({ k: v })
                  }
                ),
                /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                  Slider,
                  {
                    label: "h",
                    value: params.h,
                    min: 5,
                    max: 30,
                    step: 1,
                    onChange: (v) => setP({ h: v })
                  }
                )
              ]
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(WidgetLayout.Aside, { children: /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("ul", { style: { margin: 0, paddingLeft: 18, lineHeight: 1.55 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("li", { children: [
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "M" }),
            " \u2191 \u2014 LM shifts right, money supply line shifts right,",
            " ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "r*" }),
            " falls and ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "Y*" }),
            " rises. Monetary easing."
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("li", { children: [
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "G" }),
            " \u2191 \u2014 IS shifts right, both ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "Y*" }),
            " and",
            " ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "r*" }),
            " rise. Fiscal multiplier raises output, higher activity pushes rates up."
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("li", { children: [
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "T" }),
            " \u2191 \u2014 IS shifts left, both ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "Y*" }),
            " and",
            " ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: "r*" }),
            " fall. Tax drag."
          ] })
        ] }) })
      ]
    }
  );
}
function MoneyMarketPanel({
  params,
  eq
}) {
  const demandPts = moneyDemandPoints(params, eq.Yeq, [R_DOMAIN[0], R_DOMAIN[1]]);
  const visibleDemand = demandPts.filter(
    ([m, r]) => m >= M_DOMAIN[0] && m <= M_DOMAIN[1] && r >= R_DOMAIN[0] && r <= R_DOMAIN[1]
  );
  const demandPath = visibleDemand.length > 0 ? "M " + visibleDemand.map(([m, r]) => `${mmXScale(m).toFixed(1)} ${rScale(r).toFixed(1)}`).join(" L ") : "";
  return /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
    Frame,
    {
      width: FRAME_W,
      height: FRAME_H,
      xScale: mmXScale,
      yScale: rScale,
      xLabel: "M / P",
      yLabel: "r",
      children: () => /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(import_jsx_runtime7.Fragment, { children: [
        demandPath && /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "path",
          {
            d: demandPath,
            fill: "none",
            stroke: "var(--accent, #0969da)",
            strokeWidth: 2
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "line",
          {
            x1: mmXScale(params.M),
            y1: rScale(R_DOMAIN[1]),
            x2: mmXScale(params.M),
            y2: rScale(R_DOMAIN[0]),
            stroke: "var(--text, #1f2328)",
            strokeWidth: 1.5,
            strokeDasharray: "4 3"
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "line",
          {
            x1: 0,
            y1: rScale(eq.rEq),
            x2: INNER_W,
            y2: rScale(eq.rEq),
            stroke: "var(--text-muted, #656d76)",
            strokeWidth: 1,
            strokeDasharray: "2 4"
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "rect",
          {
            x: mmXScale(params.M) - 4,
            y: rScale(eq.rEq) - 4,
            width: 8,
            height: 8,
            fill: "var(--text, #1f2328)"
          }
        )
      ] })
    }
  ) });
}
function GoodsMarketPanel({
  params,
  eq
}) {
  const isPts = isCurvePoints(params, [R_DOMAIN[0], R_DOMAIN[1]]);
  const lmPts = lmCurvePoints(params, [Y_DOMAIN[0], Y_DOMAIN[1]]);
  const visibleIS = isPts.filter(
    ([Y, r]) => Y >= Y_DOMAIN[0] && Y <= Y_DOMAIN[1] && r >= R_DOMAIN[0] && r <= R_DOMAIN[1]
  );
  const isPath = visibleIS.length > 0 ? "M " + visibleIS.map(([Y, r]) => `${gmXScale(Y).toFixed(1)} ${rScale(r).toFixed(1)}`).join(" L ") : "";
  const visibleLM = lmPts.filter(
    ([Y, r]) => Y >= Y_DOMAIN[0] && Y <= Y_DOMAIN[1] && r >= R_DOMAIN[0] && r <= R_DOMAIN[1]
  );
  const lmPath = visibleLM.length > 0 ? "M " + visibleLM.map(([Y, r]) => `${gmXScale(Y).toFixed(1)} ${rScale(r).toFixed(1)}`).join(" L ") : "";
  return /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
    Frame,
    {
      width: FRAME_W,
      height: FRAME_H,
      xScale: gmXScale,
      yScale: rScale,
      xLabel: "Y",
      yLabel: "r",
      children: () => /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(import_jsx_runtime7.Fragment, { children: [
        isPath && /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "path",
          {
            d: isPath,
            fill: "none",
            stroke: "var(--accent, #0969da)",
            strokeWidth: 2
          }
        ),
        lmPath && /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "path",
          {
            d: lmPath,
            fill: "none",
            stroke: "#10b981",
            strokeWidth: 2
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "line",
          {
            x1: 0,
            y1: rScale(eq.rEq),
            x2: INNER_W,
            y2: rScale(eq.rEq),
            stroke: "var(--text-muted, #656d76)",
            strokeWidth: 1,
            strokeDasharray: "2 4"
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "line",
          {
            x1: gmXScale(eq.Yeq),
            y1: 0,
            x2: gmXScale(eq.Yeq),
            y2: INNER_H,
            stroke: "var(--text-muted, #656d76)",
            strokeWidth: 1,
            strokeDasharray: "2 4"
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          "rect",
          {
            x: gmXScale(eq.Yeq) - 4,
            y: rScale(eq.rEq) - 4,
            width: 8,
            height: 8,
            fill: "var(--text, #1f2328)"
          }
        )
      ] })
    }
  ) });
}
render(<IsLmExplorer />);
