// generated by @readrun/widgets — edit .readrun/widgets/kmeans-clustering.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/kmeans-clustering.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// src/figura/math/random.ts
function mulberry32(seed) {
  let s = seed >>> 0;
  return () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function boxMuller(rng = Math.random) {
  let u = 0;
  let v = 0;
  while (u === 0) u = rng();
  while (v === 0) v = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}
function sampleNormal(mu = 0, sigma = 1, rng = Math.random) {
  return mu + sigma * boxMuller(rng);
}

// readrun-docs/.readrun/widgets/kmeans-clustering.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var COLORS = ["var(--viz-trace)", "var(--viz-warn)", "var(--viz-positive)", "var(--viz-violet)", "var(--viz-pink)"];
var DEFAULT_SPEED_MS = 350;
function clearClusterAssignments(points) {
  return points.map(({ x, y }) => ({ x, y }));
}
function calculateInertia(points, centroids) {
  return points.reduce((acc, p) => {
    if (p.c === void 0) return acc;
    const c = centroids[p.c];
    if (!c) return acc;
    return acc + (p.x - c.x) ** 2 + (p.y - c.y) ** 2;
  }, 0);
}
function clampToStage(p, w, h) {
  return {
    x: Math.min(w, Math.max(0, p.x)),
    y: Math.min(h, Math.max(0, p.y))
  };
}
function nearestIndex(points, target, maxDistance) {
  let best;
  let bestDistance = maxDistance ** 2;
  points.forEach((p, i) => {
    const d = (p.x - target.x) ** 2 + (p.y - target.y) ** 2;
    if (d <= bestDistance) {
      best = i;
      bestDistance = d;
    }
  });
  return best;
}
function updatePointAt(points, index, nextPoint) {
  return points.map((p, i) => i === index ? { x: nextPoint.x, y: nextPoint.y } : p);
}
function buildDecisionCells(centroids, w, h, size) {
  if (centroids.length === 0) return [];
  const cells = [];
  for (let y = 0; y < h; y += size) {
    for (let x = 0; x < w; x += size) {
      const sample = { x: x + size / 2, y: y + size / 2 };
      cells.push({ x, y, c: nearestIndex(centroids, sample, Infinity) ?? 0, size });
    }
  }
  return cells;
}
function KmeansClustering() {
  const W = 540;
  const H = 420;
  const [k, setK] = (0, import_react4.useState)(3);
  const [points, setPoints] = (0, import_react4.useState)(() => seedPoints(W, H));
  const [centroids, setCentroids] = (0, import_react4.useState)(() => randomCentroids(3, W, H, 1));
  const [running, setRunning] = (0, import_react4.useState)(false);
  const [iter, setIter] = (0, import_react4.useState)(0);
  const [speed, setSpeed] = (0, import_react4.useState)(DEFAULT_SPEED_MS);
  const [showRegions, setShowRegions] = (0, import_react4.useState)(true);
  const [toolMode, setToolMode] = (0, import_react4.useState)("draw");
  const [dragging, setDragging] = (0, import_react4.useState)(null);
  const svgRef = (0, import_react4.useRef)(null);
  function seedPoints(w, h) {
    const rng = mulberry32(7);
    const cluster = (cx, cy, n, sd) => Array.from({ length: n }, () => ({
      x: cx + sampleNormal(0, sd, rng),
      y: cy + sampleNormal(0, sd, rng)
    }));
    return [
      ...cluster(w * 0.3, h * 0.3, 30, 28),
      ...cluster(w * 0.7, h * 0.35, 30, 28),
      ...cluster(w * 0.55, h * 0.75, 30, 32)
    ];
  }
  function randomCentroids(kk, w, h, seed) {
    const rng = mulberry32(seed);
    return Array.from({ length: kk }, () => ({ x: rng() * w, y: rng() * h }));
  }
  function step() {
    const assigned = points.map((p) => {
      let best = 0;
      let bd = Infinity;
      for (let i = 0; i < centroids.length; i++) {
        const c = centroids[i];
        const d = (p.x - c.x) ** 2 + (p.y - c.y) ** 2;
        if (d < bd) {
          bd = d;
          best = i;
        }
      }
      return { ...p, c: best };
    });
    const next = [];
    for (let i = 0; i < centroids.length; i++) {
      const ps = assigned.filter((p) => p.c === i);
      if (ps.length === 0) next.push(centroids[i]);
      else next.push({ x: ps.reduce((a, b) => a + b.x, 0) / ps.length, y: ps.reduce((a, b) => a + b.y, 0) / ps.length });
    }
    setPoints(assigned);
    setCentroids(next);
    setIter((i) => i + 1);
  }
  (0, import_react4.useEffect)(() => {
    if (!running) return;
    const id = window.setInterval(step, speed);
    return () => window.clearInterval(id);
  }, [running, points, centroids, speed]);
  const eventPoint = (e) => {
    if (!svgRef.current) return;
    const rect = svgRef.current.getBoundingClientRect();
    return clampToStage(
      {
        x: (e.clientX - rect.left) * (W / rect.width),
        y: (e.clientY - rect.top) * (H / rect.height)
      },
      W,
      H
    );
  };
  const onPointerDown = (e) => {
    const p = eventPoint(e);
    if (!p || !svgRef.current) return;
    if (toolMode === "erase") {
      const hit = nearestIndex(points, p, 14);
      if (hit !== void 0) {
        setPoints((ps) => ps.filter((_, i) => i !== hit));
        setIter(0);
      }
      return;
    }
    const centroidHit = nearestIndex(centroids, p, 18);
    if (centroidHit !== void 0) {
      setDragging({ kind: "centroid", index: centroidHit });
      svgRef.current.setPointerCapture(e.pointerId);
      return;
    }
    const pointHit = nearestIndex(points, p, 11);
    if (pointHit !== void 0) {
      setDragging({ kind: "point", index: pointHit });
      svgRef.current.setPointerCapture(e.pointerId);
      return;
    }
    setPoints((ps) => [...ps, p]);
    setIter(0);
  };
  const onPointerMove = (e) => {
    const p = eventPoint(e);
    if (!p || !dragging) return;
    if (dragging.kind === "point") {
      setPoints((ps) => updatePointAt(ps, dragging.index, p));
    } else {
      setCentroids((cs) => updatePointAt(cs, dragging.index, p));
    }
    setIter(0);
  };
  const stopDragging = (e) => {
    if (dragging && svgRef.current?.hasPointerCapture(e.pointerId)) {
      svgRef.current.releasePointerCapture(e.pointerId);
    }
    setDragging(null);
  };
  function reset() {
    setPoints(seedPoints(W, H));
    setCentroids(randomCentroids(k, W, H, Math.floor(Math.random() * 1e6)));
    setIter(0);
  }
  function clearPoints() {
    setPoints([]);
    setIter(0);
  }
  function changeK(nk) {
    setK(nk);
    setPoints((ps) => clearClusterAssignments(ps));
    setCentroids(randomCentroids(nk, W, H, Math.floor(Math.random() * 1e6)));
    setIter(0);
  }
  const inertia = calculateInertia(points, centroids);
  const decisionCells = showRegions ? buildDecisionCells(centroids, W, H, 18) : [];
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "K-Means Clustering",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "k", value: k }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "iter", value: iter }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "inertia", value: (inertia / 1e3).toFixed(1), color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Click empty space to add points. Drag points or centroids to reshape the problem, then run Lloyd iterations to watch the clusters settle." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
            "svg",
            {
              ref: svgRef,
              viewBox: `0 0 ${W} ${H}`,
              width: W,
              height: H,
              style: {
                display: "block",
                maxWidth: "100%",
                cursor: toolMode === "erase" ? "not-allowed" : dragging ? "grabbing" : "crosshair",
                touchAction: "none",
                userSelect: "none"
              },
              onPointerDown,
              onPointerMove,
              onPointerUp: stopDragging,
              onPointerCancel: stopDragging,
              onPointerLeave: stopDragging,
              children: [
                decisionCells.map((cell, i) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                  "rect",
                  {
                    x: cell.x,
                    y: cell.y,
                    width: cell.size,
                    height: cell.size,
                    fill: COLORS[cell.c % COLORS.length],
                    opacity: 0.08
                  },
                  i
                )),
                points.map((p, i) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                  "circle",
                  {
                    cx: p.x,
                    cy: p.y,
                    r: dragging?.kind === "point" && dragging.index === i ? 6 : 4,
                    fill: p.c !== void 0 ? COLORS[p.c % COLORS.length] : "var(--text-muted)",
                    opacity: p.c !== void 0 ? 0.85 : 0.5,
                    stroke: dragging?.kind === "point" && dragging.index === i ? "var(--bg)" : "none",
                    strokeWidth: dragging?.kind === "point" && dragging.index === i ? 2 : 0
                  },
                  i
                )),
                centroids.map((c, i) => /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { style: { cursor: toolMode === "erase" ? "not-allowed" : "grab" }, children: [
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                    "circle",
                    {
                      cx: c.x,
                      cy: c.y,
                      r: dragging?.kind === "centroid" && dragging.index === i ? 15 : 11,
                      fill: COLORS[i % COLORS.length],
                      stroke: "var(--bg)",
                      strokeWidth: "2.5"
                    }
                  ),
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: c.x, cy: c.y, r: 3, fill: "var(--bg)" })
                ] }, i))
              ]
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Clusters" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "k", min: 2, max: 5, step: 1, value: k, onChange: (v) => changeK(v), format: (v) => `${v}` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "speed", min: 80, max: 650, step: 10, value: speed, onChange: setSpeed, format: (v) => `${v}ms` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 8 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", active: toolMode === "draw", onClick: () => setToolMode("draw"), children: "Draw / drag" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", active: toolMode === "erase", onClick: () => setToolMode("erase"), children: "Erase" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
              "label",
              {
                style: {
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                  marginTop: 10,
                  fontSize: 11,
                  color: "var(--text-muted)"
                },
                children: [
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("input", { type: "checkbox", checked: showRegions, onChange: (e) => setShowRegions(e.currentTarget.checked) }),
                  "Show decision regions"
                ]
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 8 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: step, children: "Step" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: running ? "ghost" : "primary", onClick: () => setRunning((r) => !r), children: running ? "Stop" : "Run" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: reset, children: "Reset" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: clearPoints, children: "Clear" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Lloyd's algorithm always converges, but to a *local* minimum of inertia \u2014 different random initialisations land different cluster assignments. Click to add outliers and watch how single far points pull a centroid."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<KmeansClustering />);
