// generated by @readrun/widgets — edit .readrun/widgets/lorenz-attractor.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/lorenz-attractor.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/lorenz-attractor.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
function lorenzStep(p, sigma, rho, beta, dt) {
  const [x, y, z] = p;
  const dx = sigma * (y - x);
  const dy = x * (rho - z) - y;
  const dz = x * y - beta * z;
  return [x + dx * dt, y + dy * dt, z + dz * dt];
}
function LorenzAttractor() {
  const W = 540;
  const H = 420;
  const [sigma, setSigma] = (0, import_react4.useState)(10);
  const [rho, setRho] = (0, import_react4.useState)(28);
  const [beta, setBeta] = (0, import_react4.useState)(8 / 3);
  const [running, setRunning] = (0, import_react4.useState)(true);
  const [angle, setAngle] = (0, import_react4.useState)(0.6);
  const trail1 = (0, import_react4.useRef)([[1, 1, 1]]);
  const trail2 = (0, import_react4.useRef)([[1.0001, 1, 1]]);
  const stateRef = (0, import_react4.useRef)({ p1: [1, 1, 1], p2: [1.0001, 1, 1] });
  const [, force] = (0, import_react4.useState)(0);
  const rafRef = (0, import_react4.useRef)(0);
  (0, import_react4.useEffect)(() => {
    if (!running) return;
    const dt = 8e-3;
    const tick = () => {
      const s = stateRef.current;
      for (let k = 0; k < 5; k++) {
        s.p1 = lorenzStep(s.p1, sigma, rho, beta, dt);
        s.p2 = lorenzStep(s.p2, sigma, rho, beta, dt);
      }
      trail1.current.push(s.p1);
      trail2.current.push(s.p2);
      const max = 1500;
      if (trail1.current.length > max) trail1.current.splice(0, trail1.current.length - max);
      if (trail2.current.length > max) trail2.current.splice(0, trail2.current.length - max);
      force((n) => n + 1);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [running, sigma, rho, beta]);
  function reset() {
    stateRef.current = { p1: [1, 1, 1], p2: [1.0001, 1, 1] };
    trail1.current = [[1, 1, 1]];
    trail2.current = [[1.0001, 1, 1]];
    force((n) => n + 1);
  }
  const proj = (p) => {
    const [x, y, z] = p;
    const cx = W / 2;
    const cy = H / 2;
    const cosA = Math.cos(angle);
    const sinA = Math.sin(angle);
    const X = x * cosA - y * sinA;
    const Y = x * sinA + y * cosA;
    const scale = 9;
    return [cx + X * scale, cy - (z - 25) * scale + Y * 0.3 * scale];
  };
  const distance = (() => {
    const a = stateRef.current.p1;
    const b = stateRef.current.p2;
    return Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
  })();
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Lorenz Attractor",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u03B4", value: distance.toExponential(2), color: "var(--viz-warn)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "points", value: trail1.current.length })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Two trajectories start one part in 10\u2074 apart and diverge exponentially \u2014 a textbook chaotic system. Drag the angle slider to rotate." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polyline",
              {
                points: trail1.current.map((p) => proj(p).join(",")).join(" "),
                fill: "none",
                stroke: "var(--viz-trace)",
                strokeWidth: "1",
                opacity: "0.7"
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polyline",
              {
                points: trail2.current.map((p) => proj(p).join(",")).join(" "),
                fill: "none",
                stroke: "var(--viz-warn)",
                strokeWidth: "1",
                opacity: "0.6"
              }
            ),
            (() => {
              const [x1, y1] = proj(stateRef.current.p1);
              const [x2, y2] = proj(stateRef.current.p2);
              return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: x1, cy: y1, r: 4, fill: "var(--viz-trace)", stroke: "var(--bg)", strokeWidth: "1.5" }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: x2, cy: y2, r: 4, fill: "var(--viz-warn)", stroke: "var(--bg)", strokeWidth: "1.5" })
              ] });
            })()
          ] }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Parameters" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03C3", min: 1, max: 20, step: 0.5, value: sigma, onChange: setSigma }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03C1", min: 1, max: 50, step: 0.5, value: rho, onChange: setRho }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "\u03B2", min: 0.5, max: 5, step: 0.05, value: beta, onChange: setBeta }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "view angle", min: 0, max: Math.PI * 2, step: 0.05, value: angle, onChange: setAngle }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, marginTop: 8 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setRunning((r) => !r), children: running ? "Pause" : "Play" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: reset, children: "Reset" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " The two-lobed butterfly is the famous strange attractor. Trajectories never repeat or self-intersect, but stay bounded. Tiny initial differences (\u03B4 \u2248 10\u207B\u2074) become full-attractor scale within seconds."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<LorenzAttractor />);
