// generated by @readrun/widgets — edit .readrun/widgets/loss-landscape.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/loss-landscape.tsx
var import_react8 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}

// src/figura/plot/Frame.tsx
var import_react5 = __toESM(require_react(), 1);

// src/figura/plot/Axis.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/plot/ticks.ts
function ticks(s, n) {
  if (s.type === "ordinal") {
    return [...s.domain];
  }
  const cs = s;
  if (cs.type === "log") {
    return logTicks(cs);
  }
  return linearTicks(cs, n);
}
function linearTicks(s, n) {
  const [d0, d1] = s.domain;
  const span = d1 - d0;
  const count = Math.max(n, 2);
  const roughStep = span / count;
  const mag = Math.floor(Math.log10(roughStep));
  const base = Math.pow(10, mag);
  let step;
  const r = roughStep / base;
  if (r <= 1) {
    step = base;
  } else if (r <= 2) {
    step = 2 * base;
  } else if (r <= 5) {
    step = 5 * base;
  } else {
    step = 10 * base;
  }
  const start = Math.ceil(d0 / step) * step;
  const end = Math.floor(d1 / step) * step;
  const result = [];
  const numSteps = Math.round((end - start) / step);
  for (let i = 0; i <= numSteps; i++) {
    const v = start + i * step;
    const rounded = parseFloat(v.toPrecision(12));
    result.push(rounded);
  }
  if (result.length < 2) {
    return [d0, d1];
  }
  return result;
}
function logTicks(s) {
  const [d0, d1] = s.domain;
  const result = [];
  const logD0 = Math.log10(d0);
  const logD1 = Math.log10(d1);
  const startExp = Math.floor(logD0);
  const endExp = Math.ceil(logD1);
  for (let exp = startExp; exp <= endExp; exp++) {
    const v = Math.pow(10, exp);
    if (v >= d0 && v <= d1) {
      result.push(v);
    }
  }
  if (result.length < 2) {
    return [d0, d1];
  }
  return result;
}

// src/figura/plot/Axis.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var TICK_SIZE = 6;
var AXIS_COLOR = "#64748b";
var LABEL_COLOR = "#475569";
var FONT = "ui-monospace, monospace";
var FONT_SIZE = 11;
function Axis({
  scale: scale2,
  side,
  label,
  tickFormat = String,
  numTicks = 5
}) {
  const isHorizontal = side === "bottom" || side === "top";
  const tickValues = ticks(scale2, numTicks);
  function tickPos(value) {
    if (scale2.type === "ordinal") {
      return scale2(value);
    }
    return scale2(value);
  }
  const [r0, r1] = scale2.range;
  const lineLength = r1 - r0;
  const tickDir = side === "bottom" || side === "right" ? 1 : -1;
  if (isHorizontal) {
    const labelOffset = side === "bottom" ? TICK_SIZE + 14 : -(TICK_SIZE + 14);
    const axisLabelY = side === "bottom" ? TICK_SIZE + 28 : -(TICK_SIZE + 28);
    return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "line",
        {
          x1: r0,
          y1: 0,
          x2: r1,
          y2: 0,
          stroke: AXIS_COLOR,
          strokeWidth: 1
        }
      ),
      tickValues.map((v) => {
        const x = tickPos(v);
        return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { transform: `translate(${x}, 0)`, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "line",
            {
              x1: 0,
              y1: 0,
              x2: 0,
              y2: tickDir * TICK_SIZE,
              stroke: AXIS_COLOR,
              strokeWidth: 1
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "text",
            {
              x: 0,
              y: labelOffset,
              textAnchor: "middle",
              dominantBaseline: side === "bottom" ? "hanging" : "auto",
              style: {
                fontFamily: FONT,
                fontSize: FONT_SIZE,
                fill: LABEL_COLOR
              },
              children: tickFormat(v)
            }
          )
        ] }, String(v));
      }),
      label && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "text",
        {
          x: (r0 + r1) / 2,
          y: axisLabelY,
          textAnchor: "middle",
          dominantBaseline: side === "bottom" ? "hanging" : "auto",
          style: {
            fontFamily: FONT,
            fontSize: FONT_SIZE,
            fill: LABEL_COLOR,
            fontWeight: 500
          },
          children: label
        }
      )
    ] });
  } else {
    const labelOffset = side === "left" ? -(TICK_SIZE + 6) : TICK_SIZE + 6;
    const textAnchor = side === "left" ? "end" : "start";
    const axisLabelOffset = side === "left" ? -(TICK_SIZE + 36) : TICK_SIZE + 36;
    return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "line",
        {
          x1: 0,
          y1: r0,
          x2: 0,
          y2: lineLength < 0 ? r0 + lineLength : r1,
          stroke: AXIS_COLOR,
          strokeWidth: 1
        }
      ),
      tickValues.map((v) => {
        const y = tickPos(v);
        return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { transform: `translate(0, ${y})`, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "line",
            {
              x1: 0,
              y1: 0,
              x2: tickDir * -TICK_SIZE,
              y2: 0,
              stroke: AXIS_COLOR,
              strokeWidth: 1
            }
          ),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
            "text",
            {
              x: labelOffset,
              y: 0,
              textAnchor,
              dominantBaseline: "middle",
              style: {
                fontFamily: FONT,
                fontSize: FONT_SIZE,
                fill: LABEL_COLOR
              },
              children: tickFormat(v)
            }
          )
        ] }, String(v));
      }),
      label && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        "text",
        {
          x: axisLabelOffset,
          y: (r0 + (lineLength < 0 ? r0 + lineLength : r1)) / 2,
          textAnchor: "middle",
          transform: `rotate(-90, ${axisLabelOffset}, ${(r0 + (lineLength < 0 ? r0 + lineLength : r1)) / 2})`,
          style: {
            fontFamily: FONT,
            fontSize: FONT_SIZE,
            fill: LABEL_COLOR,
            fontWeight: 500
          },
          children: label
        }
      )
    ] });
  }
}

// src/figura/plot/Frame.tsx
var import_jsx_runtime4 = __toESM(require_jsx_runtime(), 1);
var DEFAULT_MARGIN = { top: 10, right: 10, bottom: 30, left: 40 };
function Frame({
  width,
  height,
  margin: marginProp,
  xScale,
  yScale,
  xLabel,
  yLabel,
  xTickFormat,
  yTickFormat,
  xNumTicks,
  yNumTicks,
  children
}) {
  const margin = {
    top: marginProp?.top ?? DEFAULT_MARGIN.top,
    right: marginProp?.right ?? DEFAULT_MARGIN.right,
    bottom: marginProp?.bottom ?? DEFAULT_MARGIN.bottom,
    left: marginProp?.left ?? DEFAULT_MARGIN.left
  };
  const innerWidth = width - margin.left - margin.right;
  const innerHeight = height - margin.top - margin.bottom;
  const renderArgs = {
    xScale,
    yScale,
    innerWidth,
    innerHeight
  };
  const content = typeof children === "function" ? children(renderArgs) : children;
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
    "svg",
    {
      viewBox: `0 0 ${width} ${height}`,
      width,
      height,
      style: { display: "block", maxWidth: "100%" },
      children: /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("g", { transform: `translate(${margin.left}, ${margin.top})`, children: [
        content,
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("g", { transform: `translate(0, ${innerHeight})`, children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          Axis,
          {
            scale: xScale,
            side: "bottom",
            label: xLabel,
            tickFormat: xTickFormat,
            numTicks: xNumTicks
          }
        ) }),
        /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("g", { transform: "translate(0, 0)", children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
          Axis,
          {
            scale: yScale,
            side: "left",
            label: yLabel,
            tickFormat: yTickFormat,
            numTicks: yNumTicks
          }
        ) })
      ] })
    }
  );
}

// src/figura/plot/scale.ts
function makeLinear(domain, range) {
  const [d0, d1] = domain;
  const [r0, r1] = range;
  const fn = (value) => {
    return (value - d0) / (d1 - d0) * (r1 - r0) + r0;
  };
  const s = fn;
  s.invert = (n) => (n - r0) / (r1 - r0) * (d1 - d0) + d0;
  s.domain = domain;
  s.range = range;
  s.type = "linear";
  return s;
}
function makeLog(domain, range, base) {
  const [d0, d1] = domain;
  if (d0 <= 0 || d1 <= 0) {
    throw new Error(
      `scale.log: domain values must be > 0, got [${d0}, ${d1}]`
    );
  }
  const logBase = Math.log(base);
  const logD0 = Math.log(d0) / logBase;
  const logD1 = Math.log(d1) / logBase;
  const [r0, r1] = range;
  const fn = (value) => {
    const logV = Math.log(value) / logBase;
    return (logV - logD0) / (logD1 - logD0) * (r1 - r0) + r0;
  };
  const s = fn;
  s.invert = (n) => {
    const logV = (n - r0) / (r1 - r0) * (logD1 - logD0) + logD0;
    return Math.pow(base, logV);
  };
  s.domain = domain;
  s.range = range;
  s.type = "log";
  return s;
}
function makeOrdinal(domain, range) {
  const [r0, r1] = range;
  const bw = (r1 - r0) / domain.length;
  const fn = (value) => {
    const idx = domain.indexOf(value);
    if (idx === -1) {
      throw new Error(
        `scale.ordinal: value ${String(value)} not in domain [${domain.join(", ")}]`
      );
    }
    return r0 + idx * bw + bw / 2;
  };
  const s = fn;
  s.domain = domain;
  s.range = range;
  s.bandwidth = bw;
  s.type = "ordinal";
  return s;
}
var scale = {
  linear({
    domain,
    range
  }) {
    return makeLinear(domain, range);
  },
  log({
    domain,
    range,
    base = 10
  }) {
    return makeLog(domain, range, base);
  },
  ordinal({
    domain,
    range
  }) {
    return makeOrdinal(domain, range);
  }
};

// src/figura/plot/Heatmap.tsx
var import_react6 = __toESM(require_react(), 1);
var import_jsx_runtime5 = __toESM(require_jsx_runtime(), 1);
function dataExtent(data, invalid = (v) => !Number.isFinite(v)) {
  const nx = data.length;
  if (nx === 0) return null;
  const ny = data[0].length;
  if (ny === 0) return null;
  let lo = Infinity;
  let hi = -Infinity;
  for (let i = 0; i < nx; i++) {
    const col = data[i];
    for (let j = 0; j < ny; j++) {
      const v = col[j];
      if (invalid(v)) continue;
      if (v < lo) lo = v;
      if (v > hi) hi = v;
    }
  }
  if (!Number.isFinite(lo) || !Number.isFinite(hi)) return null;
  return [lo, hi];
}
var defaultInvalid = (v) => !Number.isFinite(v);
function Heatmap({
  data,
  width,
  height,
  colorScale,
  domain,
  invalid = defaultInvalid,
  flipY = true,
  onCellClick
}) {
  const nx = data.length;
  const ny = nx > 0 ? data[0].length : 0;
  if (nx === 0 || ny === 0) {
    return /* @__PURE__ */ (0, import_jsx_runtime5.jsx)("g", {});
  }
  let lo;
  let hi;
  if (domain) {
    [lo, hi] = domain;
  } else {
    const ex = dataExtent(data, invalid);
    if (!ex) return /* @__PURE__ */ (0, import_jsx_runtime5.jsx)("g", {});
    [lo, hi] = ex;
  }
  const span = hi - lo || 1;
  const cw = width / nx;
  const ch = height / ny;
  const eps = 0.5;
  const cells = [];
  for (let i = 0; i < nx; i++) {
    const col = data[i];
    for (let j = 0; j < ny; j++) {
      const v = col[j];
      if (invalid(v)) continue;
      const t = Math.max(0, Math.min(1, (v - lo) / span));
      const x = i * cw;
      const y = flipY ? height - (j + 1) * ch : j * ch;
      cells.push(
        /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
          "rect",
          {
            x,
            y,
            width: cw + eps,
            height: ch + eps,
            fill: colorScale(t),
            ...onCellClick && {
              style: { cursor: "pointer" },
              onClick: () => onCellClick(i, j, v)
            }
          },
          `${i}-${j}`
        )
      );
    }
  }
  return /* @__PURE__ */ (0, import_jsx_runtime5.jsx)("g", { children: cells });
}

// src/figura/plot/Histogram.tsx
var import_react7 = __toESM(require_react(), 1);
var import_jsx_runtime6 = __toESM(require_jsx_runtime(), 1);

// src/figura/draw/palette.ts
function parseHex(hex) {
  if (!/^#[0-9a-fA-F]{6}$/.test(hex)) {
    throw new Error(
      `palette.sequential: invalid hex colour "${hex}". Only 6-digit hex (#rrggbb) is accepted.`
    );
  }
  const v = parseInt(hex.slice(1), 16);
  return [v >> 16 & 255, v >> 8 & 255, v & 255];
}
function toHex(r, g, b) {
  const clamp = (n) => Math.max(0, Math.min(255, Math.round(n)));
  return "#" + [clamp(r), clamp(g), clamp(b)].map((c) => c.toString(16).padStart(2, "0")).join("");
}
var VIRIDIS_STOPS = [
  "#440154",
  "#482475",
  "#414487",
  "#355f8d",
  "#2a788e",
  "#21918c",
  "#22a884",
  "#44bf70",
  "#7ad151",
  "#bddf26",
  "#fde725"
];
var MAGMA_STOPS = [
  "#000004",
  "#180f3d",
  "#440f76",
  "#721f81",
  "#9e2f7f",
  "#cd4071",
  "#f1605d",
  "#fd9668",
  "#feca8d",
  "#fcfdbf"
];
var PLASMA_STOPS = [
  "#0d0887",
  "#46039f",
  "#7201a8",
  "#9c179e",
  "#bd3786",
  "#d8576b",
  "#ed7953",
  "#fb9f3a",
  "#fdc926",
  "#f0f921"
];
function sequential(stops, t) {
  const parsed = stops.map(parseHex);
  const clamped = Math.max(0, Math.min(1, t));
  const n = parsed.length;
  if (n === 1) return toHex(...parsed[0]);
  const scaled = clamped * (n - 1);
  const lo = Math.min(Math.floor(scaled), n - 2);
  const hi = lo + 1;
  const localT = scaled - lo;
  const [r0, g0, b0] = parsed[lo];
  const [r1, g1, b1] = parsed[hi];
  return toHex(r0 + (r1 - r0) * localT, g0 + (g1 - g0) * localT, b0 + (b1 - b0) * localT);
}
var palette = {
  math: {
    accent: "#4f46e5",
    // indigo-600
    accent2: "#0ea5e9",
    // sky-500
    dim: "#cbd5e1",
    // slate-300
    surface: "#ffffff",
    text: "#0f172a",
    // slate-900
    textDim: "#475569"
    // slate-600
  },
  neuro: {
    accent: "#f87171",
    // red-400 — spike colour
    accent2: "#fbbf24",
    // amber-400 — threshold marker
    dim: "#475569",
    // slate-600 — axis lines on dark bg
    surface: "#1e293b",
    // slate-800 — dark stage
    text: "#f1f5f9",
    // slate-100
    textDim: "#94a3b8"
    // slate-400
  },
  network: {
    // six-stop sequential for degree-coloured nodes lives in sequential();
    // these fields cover axes, labels, stage
    accent: "#6366f1",
    // indigo-500 — low-degree nodes
    accent2: "#ef4444",
    // red-500 — high-degree nodes
    dim: "#334155",
    // slate-700
    surface: "#0f172a",
    // slate-900
    text: "#f8fafc",
    // slate-50
    textDim: "#94a3b8"
    // slate-400
  },
  algo: {
    accent: "#0ea5e9",
    // sky-500 — compare highlight
    accent2: "#f43f5e",
    // rose-500 — swap highlight
    dim: "#334155",
    // slate-700
    surface: "#0f172a",
    // slate-900
    text: "#f8fafc",
    textDim: "#94a3b8"
  },
  sequential,
  viridis: (t) => sequential(VIRIDIS_STOPS, t),
  magma: (t) => sequential(MAGMA_STOPS, t),
  plasma: (t) => sequential(PLASMA_STOPS, t),
  viridisStops: VIRIDIS_STOPS,
  magmaStops: MAGMA_STOPS,
  plasmaStops: PLASMA_STOPS
};

// readrun-docs/.readrun/widgets/loss-landscape.tsx
var import_jsx_runtime7 = __toESM(require_jsx_runtime(), 1);
var CMAPS = [
  { id: "viridis", label: "viridis" },
  { id: "magma", label: "magma" },
  { id: "plasma", label: "plasma" }
];
var OPTS = [
  { id: "sgd", label: "SGD" },
  { id: "momentum", label: "Momentum" }
];
var X_DOMAIN = [-2, 4];
var Y_DOMAIN = [-2, 2];
function loss(x, y) {
  return 1.2 * (x - 1) * (x - 1) + 0.6 * (y + 0.5) * (y + 0.5) + 0.6 * Math.sin(2 * x) * Math.cos(2 * y);
}
function grad(x, y) {
  return [
    2 * 1.2 * (x - 1) + 1.2 * Math.cos(2 * x) * Math.cos(2 * y),
    2 * 0.6 * (y + 0.5) - 1.2 * Math.sin(2 * x) * Math.sin(2 * y)
  ];
}
var W = 520;
var H = 380;
var INNER_W = W - 50;
var INNER_H = H - 40;
var N = 80;
function LossLandscape() {
  const [start, setStart] = (0, import_react8.useState)([-1, 1.5]);
  const [cmap, setCmap] = (0, import_react8.useState)("viridis");
  const [opt, setOpt] = (0, import_react8.useState)("momentum");
  const [lr, setLr] = (0, import_react8.useState)(0.06);
  const [steps, setSteps] = (0, import_react8.useState)(80);
  const xScale = scale.linear({ domain: X_DOMAIN, range: [0, INNER_W] });
  const yScale = scale.linear({ domain: Y_DOMAIN, range: [INNER_H, 0] });
  const grid = (0, import_react8.useMemo)(() => {
    const g = [];
    for (let i = 0; i < N; i++) {
      g[i] = [];
      for (let j = 0; j < N; j++) {
        const x = X_DOMAIN[0] + i / (N - 1) * (X_DOMAIN[1] - X_DOMAIN[0]);
        const y = Y_DOMAIN[0] + j / (N - 1) * (Y_DOMAIN[1] - Y_DOMAIN[0]);
        g[i][j] = loss(x, y);
      }
    }
    return g;
  }, []);
  const path = (0, import_react8.useMemo)(() => {
    let x = start[0];
    let y = start[1];
    let mx = 0;
    let my = 0;
    const out = [[x, y]];
    for (let i = 0; i < steps; i++) {
      const [gx, gy] = grad(x, y);
      if (opt === "sgd") {
        x -= lr * gx;
        y -= lr * gy;
      } else {
        mx = 0.9 * mx + gx;
        my = 0.9 * my + gy;
        x -= lr * mx;
        y -= lr * my;
      }
      out.push([x, y]);
    }
    return out;
  }, [start, steps, opt, lr]);
  const finalLoss = loss(path[path.length - 1][0], path[path.length - 1][1]);
  const cellToData = (i, j) => [
    X_DOMAIN[0] + i / (N - 1) * (X_DOMAIN[1] - X_DOMAIN[0]),
    Y_DOMAIN[0] + j / (N - 1) * (Y_DOMAIN[1] - Y_DOMAIN[0])
  ];
  const toScreen = (x, y) => [xScale(x), yScale(y)];
  const pathPoly = path.map(([x, y]) => toScreen(x, y).join(",")).join(" ");
  return /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(
    WidgetLayout,
    {
      arrangement: "visual-left",
      title: "Loss Landscape",
      subtitle: "Click anywhere on the heatmap to drop the start point. The optimiser path overlays in real time.",
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(WidgetLayout.Visual, { children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          Frame,
          {
            width: W,
            height: H,
            xScale,
            yScale,
            margin: { top: 10, right: 10, bottom: 30, left: 40 },
            xLabel: "x",
            yLabel: "y",
            children: ({ innerWidth, innerHeight }) => /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(import_jsx_runtime7.Fragment, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                Heatmap,
                {
                  data: grid,
                  width: innerWidth,
                  height: innerHeight,
                  colorScale: palette[cmap],
                  onCellClick: (i, j) => setStart(cellToData(i, j))
                }
              ),
              /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                "polyline",
                {
                  points: pathPoly,
                  fill: "none",
                  stroke: "var(--viz-warn)",
                  strokeWidth: 2.5,
                  opacity: 0.95,
                  pointerEvents: "none"
                }
              ),
              /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                "circle",
                {
                  cx: xScale(start[0]),
                  cy: yScale(start[1]),
                  r: 7,
                  fill: "var(--viz-warn)",
                  stroke: "var(--bg)",
                  strokeWidth: 2,
                  pointerEvents: "none"
                }
              ),
              /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
                "circle",
                {
                  cx: xScale(path[path.length - 1][0]),
                  cy: yScale(path[path.length - 1][1]),
                  r: 5,
                  fill: "var(--viz-positive)",
                  stroke: "var(--bg)",
                  strokeWidth: 1.5,
                  pointerEvents: "none"
                }
              )
            ] })
          }
        ) }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(WidgetLayout.Controls, { children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { display: "flex", gap: 16, marginBottom: 12, flexWrap: "wrap" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "loss", value: finalLoss.toFixed(4) }),
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "x", value: path[path.length - 1][0].toFixed(3) }),
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Stat, { label: "y", value: path[path.length - 1][1].toFixed(3) })
          ] }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Tabs, { value: opt, onChange: (id) => setOpt(id), items: OPTS }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Tabs, { value: cmap, onChange: (id) => setCmap(id), items: CMAPS }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Slider, { label: "learning rate", value: lr, min: 5e-3, max: 0.25, step: 5e-3, onChange: setLr }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Slider, { label: "steps", value: steps, min: 5, max: 250, step: 1, onChange: setSteps }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("div", { style: { marginTop: 8 }, children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Btn, { kind: "ghost", onClick: () => setStart([-1, 1.5]), children: "Reset start" }) })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(WidgetLayout.Aside, { children: /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("ul", { style: { margin: 0, paddingLeft: 18, lineHeight: 1.55 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("li", { children: "The surface is a paraboloid + a sin\xB7cos ripple, so optimisers can stall in local dips." }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("li", { children: "Click placements update the start; the path recomputes from there." }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("li", { children: "Momentum smooths through ripples that trap plain SGD." })
        ] }) })
      ]
    }
  );
}
render(<LossLandscape />);
