// generated by @readrun/widgets — edit .readrun/widgets/matrix-transformation.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/matrix-transformation.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}
function ToggleRow({
  checked,
  onChange,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement(
    "label",
    {
      style: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 11,
        color: "var(--text-muted)",
        cursor: "pointer"
      }
    },
    /* @__PURE__ */ import_react3.default.createElement("input", { type: "checkbox", checked, onChange: (e) => onChange(e.target.checked) }),
    children
  );
}

// src/figura/math/linalg.ts
function eig2(m) {
  const [a, b, c, d] = m;
  const tr = a + d;
  const det = a * d - b * c;
  const disc = tr * tr - 4 * det;
  if (disc < 0) return null;
  const r = Math.sqrt(disc);
  const l1 = (tr + r) / 2;
  const l2 = (tr - r) / 2;
  const evec = (l) => {
    if (Math.abs(b) > 1e-9) return [b, l - a];
    if (Math.abs(c) > 1e-9) return [l - d, c];
    return [1, 0];
  };
  const norm = (v) => {
    const n = Math.hypot(v[0], v[1]) || 1;
    return [v[0] / n, v[1] / n];
  };
  return { l1, l2, v1: norm(evec(l1)), v2: norm(evec(l2)) };
}
function decompose(m) {
  const [a, b, c, d] = m;
  const sx = Math.hypot(a, c);
  const rot = Math.atan2(c, a);
  const cosR = Math.cos(rot);
  const sinR = Math.sin(rot);
  const a2 = cosR * a + sinR * c;
  const b2 = cosR * b + sinR * d;
  const d2 = -sinR * b + cosR * d;
  const sh = a2 !== 0 ? b2 / a2 : 0;
  const sy = d2;
  return { rot, sx, sy, sh };
}

// readrun-docs/.readrun/widgets/matrix-transformation.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
function Vec({
  from,
  to,
  color,
  label,
  width = 3
}) {
  const [x1, y1] = from;
  const [x2, y2] = to;
  const ang = Math.atan2(y2 - y1, x2 - x1);
  const len = Math.hypot(x2 - x1, y2 - y1);
  const back = Math.max(len - 10, 1e-3);
  const tipX = x1 + back * Math.cos(ang);
  const tipY = y1 + back * Math.sin(ang);
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
      "line",
      {
        x1,
        y1,
        x2: tipX,
        y2: tipY,
        stroke: color,
        strokeWidth: width,
        strokeLinecap: "round"
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
      "polygon",
      {
        points: `${x2},${y2} ${tipX - 6 * Math.sin(ang)},${tipY + 6 * Math.cos(ang)} ${tipX + 6 * Math.sin(ang)},${tipY - 6 * Math.cos(ang)}`,
        fill: color
      }
    ),
    label && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
      "text",
      {
        x: x2 + 14 * Math.cos(ang) - 6,
        y: y2 + 14 * Math.sin(ang) + 5,
        fontSize: "11",
        fontWeight: "700",
        fill: color,
        fontFamily: "var(--font-body, ui-sans-serif, system-ui, sans-serif)",
        children: label
      }
    )
  ] });
}
function MatrixTransformation() {
  const W = 520;
  const H = 520;
  const S = 52;
  const cx = W / 2;
  const cy = H / 2;
  const toS = (x, y) => [cx + x * S, cy - y * S];
  const toW = (sx, sy) => [(sx - cx) / S, -(sy - cy) / S];
  const [M, setM] = (0, import_react4.useState)([1, 0, 0, 1]);
  const [pt, setPt] = (0, import_react4.useState)([1.2, 0.8]);
  const [drag, setDrag] = (0, import_react4.useState)(null);
  const [tween, setTween] = (0, import_react4.useState)(null);
  const [showEig, setShowEig] = (0, import_react4.useState)(true);
  const [decomposeMode, setDecomposeMode] = (0, import_react4.useState)(false);
  const svgRef = (0, import_react4.useRef)(null);
  (0, import_react4.useEffect)(() => {
    if (!tween) return;
    const t0 = performance.now();
    const from = [...M];
    let raf = 0;
    const dur = decomposeMode ? 1400 : 420;
    const easeOut = (t) => 1 - Math.pow(1 - t, 3);
    const step = (now) => {
      const tt = Math.min(1, (now - t0) / dur);
      let next;
      if (!decomposeMode) {
        const e = easeOut(tt);
        next = from.map((v, i) => v + (tween[i] - v) * e);
      } else {
        const tgt = decompose(tween);
        const r = tgt.rot * Math.min(1, tt * 3);
        const sx = 1 + (tgt.sx - 1) * Math.max(0, Math.min(1, tt * 3 - 1));
        const sy = 1 + (tgt.sy - 1) * Math.max(0, Math.min(1, tt * 3 - 1));
        const sh = tgt.sh * Math.max(0, Math.min(1, tt * 3 - 2));
        const cosR = Math.cos(r);
        const sinR = Math.sin(r);
        const a2 = cosR * sx;
        const b2 = cosR * (sx * sh) - sinR * sy;
        const c2 = sinR * sx;
        const d2 = sinR * (sx * sh) + cosR * sy;
        next = [a2, b2, c2, d2];
      }
      setM(next);
      if (tt < 1) raf = requestAnimationFrame(step);
      else setTween(null);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [tween]);
  const [a, b, c, d] = M;
  const det = a * d - b * c;
  const tr = a + d;
  const eig = eig2(M);
  const onPointerDown = (which) => (e) => {
    e.preventDefault();
    e.target.setPointerCapture?.(e.pointerId);
    setDrag(which);
  };
  const onPointerMove = (e) => {
    if (!drag || !svgRef.current) return;
    const rect = svgRef.current.getBoundingClientRect();
    const sx = (e.clientX - rect.left) * (W / rect.width);
    const sy = (e.clientY - rect.top) * (H / rect.height);
    const [wx, wy] = toW(sx, sy);
    const round = (v) => Math.round(v * 10) / 10;
    if (drag === "i") setM([round(wx), b, round(wy), d]);
    else if (drag === "j") setM([a, round(wx), c, round(wy)]);
    else if (drag === "p") setPt([round(wx), round(wy)]);
  };
  const onPointerUp = () => setDrag(null);
  const presets = [
    { name: "Identity", m: [1, 0, 0, 1] },
    {
      name: "Rotate 30\xB0",
      m: (() => {
        const t = Math.PI / 6;
        return [Math.cos(t), -Math.sin(t), Math.sin(t), Math.cos(t)];
      })()
    },
    { name: "Rotate 90\xB0", m: [0, -1, 1, 0] },
    { name: "Shear x", m: [1, 1, 0, 1] },
    { name: "Scale 2\xD7", m: [2, 0, 0, 2] },
    { name: "Reflect x", m: [1, 0, 0, -1] },
    { name: "Squeeze", m: [2, 0, 0, 0.5] },
    { name: "Singular", m: [1, 1, 1, 1] }
  ];
  const N = 6;
  const gridLines = [];
  for (let i = -N; i <= N; i++) {
    gridLines.push({ p1: [a * i + b * -N, c * i + d * -N], p2: [a * i + b * N, c * i + d * N], vert: true, k: i });
    gridLines.push({ p1: [a * -N + b * i, c * -N + d * i], p2: [a * N + b * i, c * N + d * i], vert: false, k: i });
  }
  const Mp = [a * pt[0] + b * pt[1], c * pt[0] + d * pt[1]];
  const [iSx, iSy] = toS(a, c);
  const [jSx, jSy] = toS(b, d);
  const [pSx, pSy] = toS(pt[0], pt[1]);
  const [mpSx, mpSy] = toS(Mp[0], Mp[1]);
  const detColor = det < 0 ? "var(--viz-warn)" : Math.abs(det) < 1e-3 ? "var(--viz-violet)" : "var(--viz-positive)";
  const fmt = (v) => Math.abs(v) < 5e-3 ? "0.00" : v.toFixed(2);
  const meta = /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "det", value: fmt(det), color: detColor }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "tr", value: fmt(tr) }),
    eig ? /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u03BB", value: `${fmt(eig.l1)}, ${fmt(eig.l2)}` }) : /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u03BB", value: "complex", color: "var(--viz-violet)" })
  ] });
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Shell, { title: "Matrix Transformation", meta, children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Sub, { children: [
      "Drag ",
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace)", fontWeight: 600 }, children: "\xEE" }),
      " and",
      " ",
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace-2)", fontWeight: 600 }, children: "\u0135" }),
      " \u2014 they form the columns of ",
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("em", { children: "M" }),
      ". The grid warps. Drag the yellow point to see its image (purple)."
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
        "svg",
        {
          ref: svgRef,
          viewBox: `0 0 ${W} ${H}`,
          width: W,
          height: H,
          style: { display: "block", touchAction: "none", maxWidth: "100%" },
          onPointerMove,
          onPointerUp,
          onPointerLeave: onPointerUp,
          children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { opacity: "0.18", children: [
              Array.from({ length: 2 * N + 1 }, (_, i) => {
                const v = i - N;
                const [x1, y1] = toS(v, -N);
                const [x2, y2] = toS(v, N);
                return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1, y1, x2, y2, stroke: "var(--viz-grid)", strokeWidth: "1" }, "ov" + v);
              }),
              Array.from({ length: 2 * N + 1 }, (_, i) => {
                const v = i - N;
                const [x1, y1] = toS(-N, v);
                const [x2, y2] = toS(N, v);
                return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1, y1, x2, y2, stroke: "var(--viz-grid)", strokeWidth: "1" }, "oh" + v);
              })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("g", { children: gridLines.map((l, i) => {
              const [x1, y1] = toS(l.p1[0], l.p1[1]);
              const [x2, y2] = toS(l.p2[0], l.p2[1]);
              const isAxis = l.k === 0;
              return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                "line",
                {
                  x1,
                  y1,
                  x2,
                  y2,
                  stroke: l.vert ? "var(--viz-trace)" : "var(--viz-trace-2)",
                  strokeWidth: isAxis ? 2 : 1,
                  opacity: isAxis ? 0.7 : 0.32
                },
                i
              );
            }) }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "polygon",
              {
                points: [
                  toS(0, 0).join(","),
                  toS(a, c).join(","),
                  toS(a + b, c + d).join(","),
                  toS(b, d).join(",")
                ].join(" "),
                fill: detColor,
                fillOpacity: "0.12",
                stroke: detColor,
                strokeWidth: "1.5",
                strokeDasharray: "2 4"
              }
            ),
            showEig && eig && [eig.v1, eig.v2].map((v, i) => {
              const [x1, y1] = toS(-N * v[0], -N * v[1]);
              const [x2, y2] = toS(N * v[0], N * v[1]);
              return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                "line",
                {
                  x1,
                  y1,
                  x2,
                  y2,
                  stroke: "var(--viz-violet)",
                  strokeWidth: "1.5",
                  strokeDasharray: "6 5",
                  opacity: "0.6"
                },
                i
              );
            }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "line",
              {
                x1: pSx,
                y1: pSy,
                x2: mpSx,
                y2: mpSy,
                stroke: "var(--viz-violet)",
                strokeWidth: "1",
                strokeDasharray: "3 3",
                opacity: "0.5"
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "circle",
              {
                cx: pSx,
                cy: pSy,
                r: 9,
                fill: "var(--viz-warn)",
                stroke: "var(--viz-violet)",
                strokeWidth: "2",
                style: { cursor: "grab" },
                onPointerDown: onPointerDown("p")
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: mpSx, cy: mpSy, r: 6, fill: "var(--viz-violet)" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Vec, { from: toS(0, 0), to: [iSx, iSy], color: "var(--viz-trace)", label: "\xEE" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Vec, { from: toS(0, 0), to: [jSx, jSy], color: "var(--viz-trace-2)", label: "\u0135" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "circle",
              {
                cx: iSx,
                cy: iSy,
                r: 11,
                fill: "var(--viz-trace)",
                stroke: "var(--bg)",
                strokeWidth: "2.5",
                style: { cursor: "grab" },
                onPointerDown: onPointerDown("i")
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "circle",
              {
                cx: jSx,
                cy: jSy,
                r: 11,
                fill: "var(--viz-trace-2)",
                stroke: "var(--bg)",
                strokeWidth: "2.5",
                style: { cursor: "grab" },
                onPointerDown: onPointerDown("j")
              }
            )
          ]
        }
      ) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 260, children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Matrix" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
          "div",
          {
            style: {
              display: "flex",
              alignItems: "center",
              gap: 4,
              fontFamily: "var(--font-mono, ui-monospace, monospace)",
              fontSize: 11,
              marginBottom: 16,
              color: "var(--text)"
            },
            children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { fontSize: 11, color: "var(--text-muted)" }, children: "[" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "0 16px" }, children: [
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace)" }, children: fmt(a) }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace-2)" }, children: fmt(b) }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace)" }, children: fmt(c) }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { color: "var(--viz-trace-2)" }, children: fmt(d) })
              ] }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("span", { style: { fontSize: 11, color: "var(--text-muted)" }, children: "]" })
            ]
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Presets" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 18 }, children: presets.map((p) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "tag", onClick: () => setTween(p.m), children: p.name }, p.name)) }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 12 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(ToggleRow, { checked: showEig, onChange: setShowEig, children: "show eigenvector directions" }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(ToggleRow, { checked: decomposeMode, onChange: setDecomposeMode, children: "decompose preset \u2192 rotate \xB7 scale \xB7 shear" })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
          " The shaded parallelogram is the image of the unit square \u2014 its signed area equals det(M). When det = 0 the plane collapses to a line. Negative det flips orientation. Eigenvector lines mark directions M only stretches.",
          decomposeMode && " \xB7 Decompose mode breaks each preset into a 3-phase animation."
        ] })
      ] })
    ] })
  ] });
}
render(<MatrixTransformation />);
