// generated by @readrun/widgets — edit .readrun/widgets/neuron-firing.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/neuron-firing.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/neuron-firing.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var Vrest = -65;
var Vthresh = -50;
var Vreset = -75;
var Vspike = 30;
function tickNeuron(s, dt, leak, baseI, coupledI) {
  const I = baseI + coupledI + s.injection;
  const dv = (-(s.v - Vrest) / leak + I) * dt;
  let v = s.v + dv;
  let spikes = s.spikes;
  if (v >= Vthresh) {
    v = Vreset;
    spikes = [...spikes, performance.now()];
  }
  const inj = s.injection > 0 ? s.injection - 4 * dt : 0;
  return { v, spikes, injection: inj };
}
function NeuronFiring() {
  const W = 700;
  const H = 320;
  const [mode, setMode] = (0, import_react4.useState)("single");
  const [leak, setLeak] = (0, import_react4.useState)(20);
  const [baseI, setBaseI] = (0, import_react4.useState)(1.4);
  const [coupling, setCoupling] = (0, import_react4.useState)(0.6);
  const [running, setRunning] = (0, import_react4.useState)(true);
  const single = (0, import_react4.useRef)({ v: Vrest, spikes: [], injection: 0 });
  const triple = (0, import_react4.useRef)([
    { v: Vrest, spikes: [], injection: 0 },
    { v: Vrest, spikes: [], injection: 0 },
    { v: Vrest, spikes: [], injection: 0 }
  ]);
  const traceRef = (0, import_react4.useRef)([[], [], []]);
  const [, force] = (0, import_react4.useState)(0);
  const rafRef = (0, import_react4.useRef)(0);
  (0, import_react4.useEffect)(() => {
    if (!running) return;
    const dt = 0.5;
    const tick = () => {
      const now = performance.now();
      if (mode === "single") {
        single.current = tickNeuron(single.current, dt, leak, baseI, 0);
        traceRef.current[0].push(single.current.v);
        if (traceRef.current[0].length > 320) traceRef.current[0].shift();
      } else {
        const ns = triple.current;
        const t = ns.map((n) => n.v);
        for (let i = 0; i < 3; i++) {
          const recentSpikes = ns.filter((_, j) => j !== i).reduce((acc, n) => acc + n.spikes.filter((s) => now - s < 50).length, 0);
          const cI = recentSpikes * coupling * 0.5;
          ns[i] = tickNeuron(ns[i], dt, leak, baseI, cI);
          traceRef.current[i].push(ns[i].v);
          if (traceRef.current[i].length > 320) traceRef.current[i].shift();
        }
      }
      const cutoff = now - 4e3;
      single.current.spikes = single.current.spikes.filter((s) => s > cutoff);
      triple.current.forEach((n) => n.spikes = n.spikes.filter((s) => s > cutoff));
      force((n) => n + 1);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [running, leak, baseI, mode, coupling]);
  function zap(i) {
    if (mode === "single") {
      single.current = { ...single.current, injection: single.current.injection + 4 };
    } else {
      triple.current[i] = { ...triple.current[i], injection: triple.current[i].injection + 4 };
    }
  }
  function reset() {
    single.current = { v: Vrest, spikes: [], injection: 0 };
    triple.current = [
      { v: Vrest, spikes: [], injection: 0 },
      { v: Vrest, spikes: [], injection: 0 },
      { v: Vrest, spikes: [], injection: 0 }
    ];
    traceRef.current = [[], [], []];
    force((n) => n + 1);
  }
  const TC = ["var(--viz-trace)", "var(--viz-warn)", "var(--viz-positive)"];
  function tracePath(t) {
    if (t.length < 2) return "";
    const ymin = Vreset - 5;
    const ymax = Vspike + 5;
    return t.map((v, i) => {
      const x = i / 320 * W;
      const y = H * 0.6 - (v - ymin) / (ymax - ymin) * H * 0.55;
      return `${i === 0 ? "M" : "L"}${x},${y}`;
    }).join(" ");
  }
  function rasterRow(spikes, y, color) {
    const now = performance.now();
    return spikes.map((s, i) => {
      const age = now - s;
      if (age > 4e3) return null;
      const x = W - age / 4e3 * W;
      return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: x, y1: y - 8, x2: x, y2: y + 8, stroke: color, strokeWidth: "1.5" }, i);
    });
  }
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Neuron Firing",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
          Stat,
          {
            label: "V",
            value: (mode === "single" ? single.current.v : triple.current[0].v).toFixed(1),
            color: "var(--viz-trace)"
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "spikes", value: (mode === "single" ? single.current.spikes : triple.current.flatMap((n) => n.spikes)).length })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Sub, { children: [
          "Leaky integrate-and-fire neuron(s). Membrane voltage decays toward rest unless input current pushes it past threshold \u2014 then a spike, then a reset. Click ",
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "Zap" }),
          " ",
          "to inject extra current."
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
          Tabs,
          {
            value: mode,
            onChange: (id) => setMode(id),
            items: [
              { id: "single", label: "Single neuron" },
              { id: "coupled", label: "3 coupled" }
            ]
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H * 0.6 - (Vthresh - (Vreset - 5)) / (Vspike + 5 - (Vreset - 5)) * H * 0.55, x2: W, y2: H * 0.6 - (Vthresh - (Vreset - 5)) / (Vspike + 5 - (Vreset - 5)) * H * 0.55, stroke: "var(--viz-warn)", strokeWidth: "1", strokeDasharray: "4 4", opacity: "0.6" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H * 0.6 - (Vrest - (Vreset - 5)) / (Vspike + 5 - (Vreset - 5)) * H * 0.55, x2: W, y2: H * 0.6 - (Vrest - (Vreset - 5)) / (Vspike + 5 - (Vreset - 5)) * H * 0.55, stroke: "var(--viz-axis)", strokeWidth: "1", strokeDasharray: "2 4", opacity: "0.4" }),
            (mode === "single" ? [traceRef.current[0]] : traceRef.current).map((t, i) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("path", { d: tracePath(t), fill: "none", stroke: TC[i], strokeWidth: "2", opacity: "0.92" }, i)),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("line", { x1: 0, y1: H - 60, x2: W, y2: H - 60, stroke: "var(--viz-axis)", strokeWidth: "1", opacity: "0.4" }),
              (mode === "single" ? [single.current.spikes] : triple.current.map((n) => n.spikes)).map((sp, i) => {
                const y = H - 30 - i * 12;
                return /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("g", { children: rasterRow(sp, y, TC[i]) }, i);
              })
            ] })
          ] }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 240, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Parameters" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "leak \u03C4", min: 5, max: 50, step: 1, value: leak, onChange: setLeak, format: (v) => `${v.toFixed(0)} ms` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "base I", min: 0, max: 3, step: 0.05, value: baseI, onChange: setBaseI }),
            mode === "coupled" && /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "coupling", min: 0, max: 2, step: 0.05, value: coupling, onChange: setCoupling }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Btn, { kind: "primary", onClick: () => zap(0), children: [
                "\u26A1 Zap ",
                mode === "coupled" ? "n1" : ""
              ] }),
              mode === "coupled" && /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => zap(1), children: "\u26A1 n2" }),
                /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => zap(2), children: "\u26A1 n3" })
              ] }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setRunning((r) => !r), children: running ? "Pause" : "Play" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: reset, children: "Reset" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " The orange dashed line is the firing threshold (V_th = -50 mV). When voltage crosses it, the neuron emits a spike and resets to V_reset (-75 mV). In coupled mode, each spike from a neighbour gives a small bump \u2014 you can see waves propagate."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<NeuronFiring />);
