// generated by @readrun/widgets — edit .readrun/widgets/sort-tracer.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/sort-tracer.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Tabs({
  value,
  onChange,
  items
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-tabs" }, items.map((it) => /* @__PURE__ */ import_react3.default.createElement(
    "button",
    {
      key: it.id,
      className: `viz-tab${value === it.id ? " active" : ""}`,
      onClick: () => onChange(it.id)
    },
    it.label
  )));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function LegendDot({ color, label }) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-legend-dot" }, /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-dot", style: { background: color } }), label);
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// src/figura/math/random.ts
function mulberry32(seed) {
  let s = seed >>> 0;
  return () => {
    s = s + 1831565813 >>> 0;
    let t = s;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

// readrun-docs/.readrun/widgets/sort-tracer.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
var ALGOS = [
  { id: "bubble", label: "Bubble" },
  { id: "insertion", label: "Insertion" },
  { id: "selection", label: "Selection" },
  { id: "quick", label: "Quick" },
  { id: "merge", label: "Merge" },
  { id: "heap", label: "Heap" }
];
function bubble(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  const locked = [];
  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < a.length - i - 1; j++) {
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [j, j + 1], swap: null, locked: locked.slice(), cmpCount, swapCount });
      if (a[j] > a[j + 1]) {
        [a[j], a[j + 1]] = [a[j + 1], a[j]];
        swapCount++;
        frames.push({ arr: a.slice(), cmp: null, swap: [j, j + 1], locked: locked.slice(), cmpCount, swapCount });
      }
    }
    locked.unshift(a.length - i - 1);
  }
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
function insertion(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  for (let i = 1; i < a.length; i++) {
    let j = i;
    while (j > 0) {
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [j - 1, j], swap: null, locked: [], cmpCount, swapCount });
      if (a[j - 1] > a[j]) {
        [a[j - 1], a[j]] = [a[j], a[j - 1]];
        swapCount++;
        frames.push({ arr: a.slice(), cmp: null, swap: [j - 1, j], locked: [], cmpCount, swapCount });
        j--;
      } else break;
    }
  }
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
function selection(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  const locked = [];
  for (let i = 0; i < a.length; i++) {
    let min = i;
    for (let j = i + 1; j < a.length; j++) {
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [min, j], swap: null, locked: locked.slice(), cmpCount, swapCount });
      if (a[j] < a[min]) min = j;
    }
    if (min !== i) {
      [a[i], a[min]] = [a[min], a[i]];
      swapCount++;
      frames.push({ arr: a.slice(), cmp: null, swap: [i, min], locked: locked.slice(), cmpCount, swapCount });
    }
    locked.push(i);
  }
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
function quick(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  const locked = [];
  function qs(lo, hi) {
    if (lo >= hi) {
      if (lo === hi) locked.push(lo);
      return;
    }
    const pivot = hi;
    let i = lo;
    for (let j = lo; j < hi; j++) {
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [j, pivot], swap: null, pivot, locked: locked.slice(), cmpCount, swapCount });
      if (a[j] < a[pivot]) {
        if (i !== j) {
          [a[i], a[j]] = [a[j], a[i]];
          swapCount++;
          frames.push({ arr: a.slice(), cmp: null, swap: [i, j], pivot, locked: locked.slice(), cmpCount, swapCount });
        }
        i++;
      }
    }
    if (i !== pivot) {
      [a[i], a[pivot]] = [a[pivot], a[i]];
      swapCount++;
      frames.push({ arr: a.slice(), cmp: null, swap: [i, pivot], pivot: i, locked: locked.slice(), cmpCount, swapCount });
    }
    locked.push(i);
    qs(lo, i - 1);
    qs(i + 1, hi);
  }
  qs(0, a.length - 1);
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
function merge(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  function ms(lo, hi) {
    if (hi - lo < 1) return;
    const mid = Math.floor((lo + hi) / 2);
    ms(lo, mid);
    ms(mid + 1, hi);
    const merged = [];
    let i = lo;
    let j = mid + 1;
    while (i <= mid && j <= hi) {
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [i, j], swap: null, locked: [], cmpCount, swapCount });
      if (a[i] <= a[j]) merged.push(a[i++]);
      else merged.push(a[j++]);
    }
    while (i <= mid) merged.push(a[i++]);
    while (j <= hi) merged.push(a[j++]);
    for (let k = 0; k < merged.length; k++) {
      a[lo + k] = merged[k];
      swapCount++;
    }
    frames.push({ arr: a.slice(), cmp: null, swap: [lo, hi], locked: [], cmpCount, swapCount });
  }
  ms(0, a.length - 1);
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
function heap(arr) {
  const a = arr.slice();
  const frames = [];
  let cmpCount = 0;
  let swapCount = 0;
  const locked = [];
  const sift = (start, end) => {
    let root = start;
    while (root * 2 + 1 <= end) {
      let child = root * 2 + 1;
      if (child + 1 <= end) {
        cmpCount++;
        if (a[child] < a[child + 1]) child++;
      }
      cmpCount++;
      frames.push({ arr: a.slice(), cmp: [root, child], swap: null, locked: locked.slice(), cmpCount, swapCount });
      if (a[root] < a[child]) {
        [a[root], a[child]] = [a[child], a[root]];
        swapCount++;
        frames.push({ arr: a.slice(), cmp: null, swap: [root, child], locked: locked.slice(), cmpCount, swapCount });
        root = child;
      } else break;
    }
  };
  for (let i = Math.floor(a.length / 2) - 1; i >= 0; i--) sift(i, a.length - 1);
  for (let end = a.length - 1; end > 0; end--) {
    [a[0], a[end]] = [a[end], a[0]];
    swapCount++;
    locked.unshift(end);
    frames.push({ arr: a.slice(), cmp: null, swap: [0, end], locked: locked.slice(), cmpCount, swapCount });
    sift(0, end - 1);
  }
  locked.unshift(0);
  frames.push({ arr: a.slice(), cmp: null, swap: null, locked: a.map((_, i) => i), cmpCount, swapCount });
  return frames;
}
var RUNNERS = {
  bubble,
  insertion,
  selection,
  quick,
  merge,
  heap
};
function SortTracer() {
  const W = 720;
  const H = 320;
  const [algo, setAlgo] = (0, import_react4.useState)("quick");
  const [size, setSize] = (0, import_react4.useState)(20);
  const [seed, setSeed] = (0, import_react4.useState)(7);
  const [step, setStep] = (0, import_react4.useState)(0);
  const arr = (0, import_react4.useMemo)(() => {
    const rng = mulberry32(seed);
    return Array.from({ length: size }, () => Math.floor(rng() * 100) + 1);
  }, [size, seed]);
  const frames = (0, import_react4.useMemo)(() => RUNNERS[algo](arr), [algo, arr]);
  const safeStep = Math.min(step, frames.length - 1);
  const f = frames[safeStep];
  const max = Math.max(...f.arr);
  const bw = W / f.arr.length;
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Sort Tracer",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "cmps", value: f.cmpCount, color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "swaps", value: f.swapCount, color: "var(--viz-warn)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "step", value: `${safeStep + 1}/${frames.length}` })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Step through six classical sorting algorithms. Color codes: comparisons are blue, swaps are orange, the active pivot is violet, locked-in (sorted) positions are green." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Tabs, { value: algo, onChange: (id) => {
          setAlgo(id);
          setStep(0);
        }, items: ALGOS }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("svg", { viewBox: `0 0 ${W} ${H}`, width: W, height: H, style: { display: "block", maxWidth: "100%" }, children: f.arr.map((v, i) => {
            const x = i * bw;
            const h = v / max * (H - 30);
            let fill = "var(--viz-axis)";
            if (f.locked.includes(i)) fill = "var(--viz-positive)";
            if (f.cmp && (f.cmp[0] === i || f.cmp[1] === i)) fill = "var(--viz-trace)";
            if (f.swap && (f.swap[0] === i || f.swap[1] === i)) fill = "var(--viz-warn)";
            if (f.pivot === i) fill = "var(--viz-violet)";
            return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("g", { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("rect", { x: x + 1, y: H - 18 - h, width: bw - 2, height: h, fill }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
                "text",
                {
                  x: x + bw / 2,
                  y: H - 4,
                  fontSize: "11",
                  textAnchor: "middle",
                  fill: "var(--text-muted)",
                  fontFamily: "var(--font-mono, monospace)",
                  children: v
                }
              )
            ] }, i);
          }) }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 240, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Controls" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setStep((s) => Math.max(0, s - 1)), children: "\u2039 Back" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setStep((s) => Math.min(frames.length - 1, s + 1)), children: "Step \u203A" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setStep(frames.length - 1), children: "End \u23ED" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => setStep(0), children: "Reset" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Array" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "size", min: 6, max: 36, step: 1, value: size, onChange: (v) => {
              setSize(v);
              setStep(0);
            }, format: (v) => `${v}` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "seed", min: 1, max: 50, step: 1, value: seed, onChange: (v) => {
              setSeed(v);
              setStep(0);
            }, format: (v) => `${v}` }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { style: { marginTop: 8 }, children: "Legend" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-trace)", label: "comparing" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-warn)", label: "swapping" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-violet)", label: "pivot" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(LegendDot, { color: "var(--viz-positive)", label: "locked" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Bubble and insertion are O(n\xB2); merge and heap are O(n log n) worst-case; quick is O(n log n) average but O(n\xB2) on adversarial input. Watch the swap count \u2014 merge sort uses no in-place swaps but it does write every element back."
            ] })
          ] })
        ] })
      ]
    }
  );
}
render(<SortTracer />);
