// generated by @readrun/widgets — edit .readrun/widgets/wave-interference.tsx, then re-run rr
// @readrun/widgets@e12f9c0 — generated 2026-05-12T01:57:41Z
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// globals:react
var require_react = __commonJS({
  "globals:react"(exports, module) {
    module.exports = globalThis.React;
  }
});

// globals:react/jsx-runtime
var require_jsx_runtime = __commonJS({
  "globals:react/jsx-runtime"(exports, module) {
    module.exports = globalThis.React;
  }
});

// readrun-docs/.readrun/widgets/wave-interference.tsx
var import_react4 = __toESM(require_react(), 1);

// src/figura/primitives/index.tsx
var import_react3 = __toESM(require_react());

// src/figura/primitives/WidgetLayout.tsx
var import_react = __toESM(require_react(), 1);
var import_jsx_runtime = __toESM(require_jsx_runtime(), 1);
function VisualSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function ControlsSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
function AsideSlot({ children }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_jsx_runtime.Fragment, { children });
}
VisualSlot.__figuraSlot = "visual";
ControlsSlot.__figuraSlot = "controls";
AsideSlot.__figuraSlot = "aside";
function extractSlots(children) {
  const slots = {};
  import_react.default.Children.forEach(children, (child) => {
    if (import_react.default.isValidElement(child)) {
      const t = child.type;
      if (t?.__figuraSlot) {
        slots[t.__figuraSlot] = child;
      }
    }
  });
  return slots;
}
function WidgetLayoutImpl(props) {
  const arrangement = props.arrangement ?? "visual-left";
  const slots = extractSlots(props.children);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `figura-widget figura-widget--${arrangement}`, children: [
    (props.title || props.subtitle || props.headMeta) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        className: "figura-widget__head",
        style: { display: "flex", justifyContent: "space-between" },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
            props.title && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { className: "figura-widget__title", children: props.title }),
            props.subtitle && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__subtitle", children: props.subtitle })
          ] }),
          props.headMeta && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { children: props.headMeta })
        ]
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__body", children: [
      slots["visual"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__visual", children: slots["visual"] }),
      (slots["controls"] || slots["aside"]) && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__sidebar", children: [
        slots["controls"] && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__controls", children: slots["controls"] }),
        slots["aside"] && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "figura-widget__aside", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "figura-widget__aside-label", children: "What to notice" }),
          slots["aside"]
        ] })
      ] })
    ] })
  ] });
}
var WidgetLayout = Object.assign(WidgetLayoutImpl, {
  Visual: VisualSlot,
  Controls: ControlsSlot,
  Aside: AsideSlot
});

// src/figura/primitives/FormulaSteps.tsx
var import_react2 = __toESM(require_react(), 1);
var import_jsx_runtime2 = __toESM(require_jsx_runtime(), 1);

// src/figura/primitives/index.tsx
function Shell({
  title,
  meta,
  children
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell" }, (title || meta) && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-head" }, title && /* @__PURE__ */ import_react3.default.createElement("h2", null, title), meta && /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-shell-meta" }, meta)), children);
}
function Sub({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("p", { className: "viz-sub" }, children);
}
function SectionLabel({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-section-label", style }, children);
}
function Stage({
  children,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-stage", style }, children);
}
function Panel({
  children,
  minWidth = 240,
  style
}) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-panel", style: { minWidth, ...style } }, children);
}
function Btn({
  kind = "ghost",
  active,
  children,
  ...rest
}) {
  const cls = `viz-btn viz-btn-${kind}${active ? " viz-btn-active" : ""}`;
  return /* @__PURE__ */ import_react3.default.createElement("button", { className: cls, ...rest }, children);
}
function Slider({
  label,
  unit,
  min,
  max,
  step = 1,
  value,
  onChange,
  format
}) {
  const fmt = format || ((v) => Number.isFinite(v) ? v.toFixed(2) : String(v));
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-row" }, /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-slider-head" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-value" }, fmt(value), unit && /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-slider-unit" }, unit))), /* @__PURE__ */ import_react3.default.createElement(
    "input",
    {
      type: "range",
      min,
      max,
      step,
      value,
      onChange: (e) => onChange(+e.target.value)
    }
  ));
}
function Stat({
  label,
  value,
  color
}) {
  return /* @__PURE__ */ import_react3.default.createElement("span", { className: "viz-stat" }, /* @__PURE__ */ import_react3.default.createElement("span", null, label), /* @__PURE__ */ import_react3.default.createElement("strong", { className: "viz-stat-value", style: color ? { color } : void 0 }, value));
}
function Notice({ children }) {
  return /* @__PURE__ */ import_react3.default.createElement("div", { className: "viz-notice" }, children);
}

// readrun-docs/.readrun/widgets/wave-interference.tsx
var import_jsx_runtime3 = __toESM(require_jsx_runtime(), 1);
function WaveInterference() {
  const W = 540;
  const H = 360;
  const [s1, setS1] = (0, import_react4.useState)([180, 120]);
  const [s2, setS2] = (0, import_react4.useState)([360, 240]);
  const [freq, setFreq] = (0, import_react4.useState)(0.06);
  const [phase, setPhase] = (0, import_react4.useState)(0);
  const [t, setT] = (0, import_react4.useState)(0);
  const [running, setRunning] = (0, import_react4.useState)(true);
  const dragRef = (0, import_react4.useRef)(null);
  const svgRef = (0, import_react4.useRef)(null);
  const canvasRef = (0, import_react4.useRef)(null);
  (0, import_react4.useEffect)(() => {
    if (!running) return;
    const id = window.setInterval(() => setT((tt) => tt + 0.15), 60);
    return () => window.clearInterval(id);
  }, [running]);
  (0, import_react4.useEffect)(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const cw = W;
    const ch = H;
    if (canvas.width !== cw) canvas.width = cw;
    if (canvas.height !== ch) canvas.height = ch;
    const ctx = canvas.getContext("2d");
    const img = ctx.createImageData(cw, ch);
    const accent = getCss("--viz-trace") || "#3b82f6";
    const accent2 = getCss("--viz-warn") || "#f59e0b";
    const [r1, g1, b1] = hexToRgb(resolveColor(accent));
    const [r2, g2, b2] = hexToRgb(resolveColor(accent2));
    const stride = 2;
    for (let y = 0; y < ch; y += stride) {
      for (let x = 0; x < cw; x += stride) {
        const d1 = Math.hypot(x - s1[0], y - s1[1]);
        const d2 = Math.hypot(x - s2[0], y - s2[1]);
        const v = Math.sin(d1 * freq - t) + Math.sin(d2 * freq - t + phase);
        const norm = (v + 2) / 4;
        const r = Math.round(r1 * norm + r2 * (1 - norm));
        const g = Math.round(g1 * norm + g2 * (1 - norm));
        const b = Math.round(b1 * norm + b2 * (1 - norm));
        for (let dy = 0; dy < stride; dy++) {
          for (let dx = 0; dx < stride; dx++) {
            const idx = ((y + dy) * cw + (x + dx)) * 4;
            img.data[idx] = r;
            img.data[idx + 1] = g;
            img.data[idx + 2] = b;
            img.data[idx + 3] = 255;
          }
        }
      }
    }
    ctx.putImageData(img, 0, 0);
  });
  function pos(e) {
    const rect = svgRef.current.getBoundingClientRect();
    return [(e.clientX - rect.left) * (W / rect.width), (e.clientY - rect.top) * (H / rect.height)];
  }
  function down(e) {
    const [x, y] = pos(e);
    const d1 = Math.hypot(x - s1[0], y - s1[1]);
    const d2 = Math.hypot(x - s2[0], y - s2[1]);
    if (d1 < 24 && d1 < d2) dragRef.current = "s1";
    else if (d2 < 24) dragRef.current = "s2";
  }
  function move(e) {
    if (!dragRef.current) return;
    const [x, y] = pos(e);
    if (dragRef.current === "s1") setS1([x, y]);
    else setS2([x, y]);
  }
  function up() {
    dragRef.current = null;
  }
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
    Shell,
    {
      title: "Wave Interference",
      meta: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(import_jsx_runtime3.Fragment, { children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "freq", value: freq.toFixed(3), color: "var(--viz-trace)" }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stat, { label: "\u0394\u03C6", value: phase.toFixed(2), color: "var(--viz-warn)" })
      ] }),
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Sub, { children: "Two coherent point sources. Where peaks meet peaks (constructive interference) you see the accent colour; where peaks meet troughs (destructive) you see the warn colour. Drag either source." }),
        /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { className: "viz-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Stage, { children: /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { position: "relative", width: W, height: H, maxWidth: "100%" }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
              "canvas",
              {
                ref: canvasRef,
                style: { display: "block", width: "100%", height: "100%", borderRadius: 8 }
              }
            ),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(
              "svg",
              {
                ref: svgRef,
                viewBox: `0 0 ${W} ${H}`,
                width: W,
                height: H,
                style: { display: "block", position: "absolute", top: 0, left: 0, touchAction: "none", maxWidth: "100%" },
                onPointerDown: down,
                onPointerMove: move,
                onPointerUp: up,
                onPointerLeave: up,
                children: [
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: s1[0], cy: s1[1], r: 10, fill: "var(--bg)", stroke: "var(--text)", strokeWidth: "2", style: { cursor: "grab" } }),
                  /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("circle", { cx: s2[0], cy: s2[1], r: 10, fill: "var(--bg)", stroke: "var(--text)", strokeWidth: "2", style: { cursor: "grab" } })
                ]
              }
            )
          ] }) }),
          /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Panel, { minWidth: 220, children: [
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(SectionLabel, { children: "Wave parameters" }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "frequency", min: 0.02, max: 0.18, step: 5e-3, value: freq, onChange: setFreq }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Slider, { label: "phase \u0394", min: 0, max: Math.PI * 2, step: 0.05, value: phase, onChange: setPhase }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", gap: 6, marginTop: 8 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "primary", onClick: () => setRunning((r) => !r), children: running ? "Pause" : "Play" }),
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Btn, { kind: "ghost", onClick: () => {
                setS1([180, 120]);
                setS2([360, 240]);
                setPhase(0);
              }, children: "Reset" })
            ] }),
            /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Notice, { children: [
              /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("strong", { children: "What to notice." }),
              " Hyperbolic fringes appear because constructive interference happens where path-length difference is a whole multiple of wavelength. Move the sources together \u2014 the fringes spread; pull them apart \u2014 they tighten."
            ] })
          ] })
        ] })
      ]
    }
  );
}
function getCss(name) {
  if (typeof window === "undefined") return "";
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}
function resolveColor(s) {
  if (!s) return "#3b82f6";
  if (s.startsWith("#")) return s;
  if (s.startsWith("rgb")) {
    const m = s.match(/\d+/g);
    if (m && m.length >= 3) {
      const [r, g, b] = m.map((v) => parseInt(v, 10));
      return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
    }
  }
  return "#3b82f6";
}
function hexToRgb(hex) {
  const h = hex.replace("#", "");
  if (h.length === 3) {
    return [parseInt(h[0] + h[0], 16), parseInt(h[1] + h[1], 16), parseInt(h[2] + h[2], 16)];
  }
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}
render(<WaveInterference />);
