import { describe, it, expect, beforeAll } from "bun:test";
import * as fs from "fs";
import {
  kebabToPascal,
  stripExports,
  extractDefaultExportName,
  bundleWidget,
} from "./bundler";

// ─── 1. kebabToPascal ────────────────────────────────────────────────────────

describe("kebabToPascal", () => {
  it("converts multi-word kebab to PascalCase", () => {
    expect(kebabToPascal("distribution-explorer")).toBe("DistributionExplorer");
    expect(kebabToPascal("force-graph")).toBe("ForceGraph");
    expect(kebabToPascal("foo-bar-baz")).toBe("FooBarBaz");
  });

  it("converts single word (no dash)", () => {
    expect(kebabToPascal("widget")).toBe("Widget");
  });

  it("converts single-letter segments", () => {
    expect(kebabToPascal("a-b-c")).toBe("ABC");
  });
});

// ─── 2. stripExports ────────────────────────────────────────────────────────

describe("stripExports", () => {
  it("removes export { Foo as default }", () => {
    const input = `function Foo() {}\nexport { Foo as default };\n`;
    const result = stripExports(input);
    expect(result).not.toMatch(/^export\s/m);
    expect(result).toContain("function Foo");
  });

  it("removes multiple export lines", () => {
    const input = `const x = 1;\nexport { x };\nexport const y = 2;\nexport * from "other";\nconst z = 3;\n`;
    const result = stripExports(input);
    expect(result).not.toMatch(/^export\s/m);
    expect(result).toContain("const x = 1");
    expect(result).toContain("const z = 3");
  });

  it("leaves source unchanged when no exports present", () => {
    const input = `function Foo() {}\nFoo();\n`;
    expect(stripExports(input)).toBe(input);
  });

  it("removes export * lines", () => {
    const input = `export * from "other";\nfunction Bar() {}\n`;
    const result = stripExports(input);
    expect(result).not.toContain("export *");
    expect(result).toContain("function Bar");
  });

  it("removes multi-line export { ... } block (esbuild style)", () => {
    const input = `function Foo() {}\nexport {\n  Foo as default\n};\n`;
    const result = stripExports(input);
    expect(result).not.toMatch(/^export/m);
    expect(result).toContain("function Foo");
    // stray lines from the block body must also be gone
    expect(result).not.toContain("Foo as default");
  });
});

// ─── 3. extractDefaultExportName ────────────────────────────────────────────

describe("extractDefaultExportName", () => {
  it("finds name from export default function Foo() {}", () => {
    const src = `export default function Foo() { return null; }`;
    expect(extractDefaultExportName(src)).toBe("Foo");
  });

  it("finds name from function Foo then export default Foo", () => {
    const src = `function Foo() { return null; }\nexport default Foo;`;
    expect(extractDefaultExportName(src)).toBe("Foo");
  });

  it("finds name from const Foo = () => {} then export default Foo", () => {
    const src = `const Foo = () => null;\nexport default Foo;`;
    expect(extractDefaultExportName(src)).toBe("Foo");
  });

  it("returns null when no default export present", () => {
    const src = `export function Foo() { return null; }`;
    expect(extractDefaultExportName(src)).toBeNull();
  });
});

// ─── 4. bundleWidget integration ────────────────────────────────────────────

const TMP_DIR = "/tmp/figura-test";
const WIDGETS_DIR = `${TMP_DIR}/widgets`;
const OUT_DIR = `${TMP_DIR}/out`;

beforeAll(() => {
  fs.mkdirSync(WIDGETS_DIR, { recursive: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  fs.writeFileSync(
    `${WIDGETS_DIR}/foo-bar.tsx`,
    `import React from "react";\n\nexport default function FooBar() {\n  return <div>hello {React.version}</div>;\n}\n`
  );
});

const TOOLKIT_ROOT = "/home/eastill/projects/readrun/src/figura";

describe("bundleWidget integration", () => {
  it("produces output with correct shape", async () => {
    const result = await bundleWidget("foo-bar", {
      widgetsDir: WIDGETS_DIR,
      toolkitRoot: TOOLKIT_ROOT,
    });

    // No import statements
    expect(result).not.toMatch(/^import\s/m);

    // No export statements
    expect(result).not.toMatch(/^export\s/m);

    // Contains the component name
    expect(result).toMatch(/\bFooBar\b/);

    // Ends with render call
    expect(result.trimEnd()).toMatch(/render\(<FooBar\s*\/>\);?$/m);

    // Starts with the banner
    expect(result).toMatch(/^\/\/ generated by @readrun\/widgets/m);

    // References globalThis.React somewhere
    expect(result).toContain("globalThis.React");
  });
});

// ─── 5. Banner format ────────────────────────────────────────────────────────

import { buildBanner, isGeneratedBanner } from "./bundler";

describe("buildBanner", () => {
  it("contains two lines with the correct structure", () => {
    const banner = buildBanner("foo-bar", TOOLKIT_ROOT);
    const lines = banner.split("\n").filter(Boolean);

    expect(lines[0]).toMatch(/\/\/ generated by @readrun\/widgets — edit \.readrun\/widgets\/foo-bar\.tsx/);
    expect(lines[1]).toMatch(/\/\/ @readrun\/widgets@[0-9a-f]{7}/);
  });

  it("SHA is 7 hex characters", () => {
    const banner = buildBanner("any", TOOLKIT_ROOT);
    const match = banner.match(/@readrun\/widgets@([0-9a-f]+)/);
    expect(match).not.toBeNull();
    expect(match![1]).toHaveLength(7);
  });
});

describe("isGeneratedBanner", () => {
  it("detects banner produced by buildBanner", () => {
    const banner = buildBanner("foo", TOOLKIT_ROOT);
    expect(isGeneratedBanner(banner)).toBe(true);
  });

  it("returns false for hand-written code", () => {
    expect(isGeneratedBanner("function Foo(){}\nrender(<Foo/>);")).toBe(false);
    expect(isGeneratedBanner("// some other comment\nfunction Bar(){}")).toBe(false);
  });
});
